### ISSUE TITLE
[Feature] Open metrics support

### ISSUE THREAD

**Issue by Project0** [rspamd/rspamd#3706] opened 2021-04-06 13:54 UTC
## Summary

I would love to see open metrics (prometheus) support :smile:

similar to the auto closed #2870 (why are feature requests auto closed...)

## Motivation

The open metrics format is widely adopted by different monitoring systems, so it would be great to use them in the modern art of observability. 
It would be awesome if i can re-use my existing prometheus setup (and do not need to build a wraper to catch the graphite metrics) to visualize all the cool metrics exists.

**Comment by mrueg** [comment] 2021-04-09 22:55
See this as well: https://github.com/rspamd/rspamd/discussions/3484 (it was an issue before that got moved into a discussion)

**Comment by vstakhov** [comment] 2021-04-10 14:40
Duplicate of #3484 .

**Closed by vstakhov** 2021-04-10 14:40 UTC
Labels: enhancement

**Comment by Project0** [comment] 2021-04-12 15:39
i was not aware github discussions are used to track feature requests :+1:
