### ISSUE TITLE
Normal worker doesn't work with Unix sockets: proxy worker returns error "can't read SMFIC_BODYEOB"

### ISSUE THREAD

**Issue by iq180** [rspamd/rspamd#2241] opened 2018-05-12 12:39 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.2-1.7.4
### Operation system, CPU, memory and environment:
4.16.8-gentoo SMP x86_64 Intel(R) Xeon(R) CPU X3430 @ 2.40GHz GenuineIntel GNU/Linux
### Description (Please provide a descriptive summary of the issue):
Normal worker doesn't work with Unix sockets: proxy worker returns error "can't read SMFIC_BODYEOB"
### Steps to reproduce:
/etc/rspamd/override.d/worker-proxy.inc:
`bind_socket = "/var/run/rspamd/rspamd-proxy.sock mode=0666 owner=_rspamd";`
/etc/rspamd/override.d/worker-normal.inc:
`bind_socket = "/var/run/rspamd/rspamd-normal.sock mode=0666 owner=_rspamd";`
### Actual results:
journalctl -r -b:
```
май 12 14:16:47 srv4 postfix/smtpd[7747]: disconnect from ...[...] ehlo=1 mail=1 rcpt=1 data=0/1 quit=1 commands=4/5
май 12 14:16:47 srv4 postfix/cleanup[7750]: CDFBD1E151C: milter-reject: END-OF-MESSAGE from ...[...]: 4.7.1 Service unavailable - try again later; from=<...> to=<...> proto=ESMTP helo=<...>
май 12 14:16:47 srv4 postfix/cleanup[7750]: warning: milter unix:/var/run/rspamd/rspamd-proxy.sock: can't read SMFIC_BODYEOB reply packet header: Success
май 12 14:16:47 srv4 postfix/cleanup[7750]: CDFBD1E151C: message-id=<1526123806.820803590@...>
май 12 14:16:47 srv4 postfix/smtpd[7747]: CDFBD1E151C: client=...[...]
май 12 14:16:47 srv4 postfix/smtpd[7747]: connect from ...[...]
```
/var/log/rspamd/rspamd.log:
```
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_accept_socket: accepted milter connection from /var/run/rspamd/rspamd-proxy.sock port 0
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; milter; rspamd_milter_process_command: got connection from ...:...
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: abnormally closing connection from backend: ::1, error: IO write error: Connection refused, retries left: 5
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: retry connection to: 127.0.0.1 retries left: 4
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: abnormally closing connection from backend: 127.0.0.1, error: IO write error: Connection refused, retries left: 4
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: retry connection to: ::1 retries left: 3
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: abnormally closing connection from backend: 127.0.0.1, error: IO write error: Connection refused, retries left: 3
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: retry connection to: ::1 retries left: 2
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: abnormally closing connection from backend: ::1, error: IO write error: Connection refused, retries left: 2
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: retry connection to: 127.0.0.1 retries left: 1
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: abnormally closing connection from backend: ::1, error: IO write error: Connection refused, retries left: 1
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: retry connection to: 127.0.0.1 retries left: 0
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: abnormally closing connection from backend: 127.0.0.1, error: IO write error: Connection refused, retries left: 0
2018-05-12 14:16:47 #7708(rspamd_proxy) <2831c7>; proxy; proxy_backend_master_error_handler: cannot connect to upstream, maximum retries has been reached: 6
```
### Additional information:
If normal worker is bound to TCP port, everything's fine.

**Comment by vstakhov** [comment] 2018-05-12 12:42
That's expected: set proxy to point the normal worker (e.g. set the proper upstream for it) as by default it tries to connect to a TCP socket. Closing issue, not a bug.

**Comment by iq180** [comment] 2018-05-12 13:43
So what am I doing wrong?

/etc/rspamd/override.d/worker-normal.inc:
`bind_socket = "/var/run/rspamd/rspamd-normal.sock mode=0666 owner=_rspamd";`

/etc/rspamd/override.d/worker-proxy.inc:
```
bind_socket = "/var/run/rspamd/rspamd-proxy.sock mode=0666 owner=_rspamd";

upstream "local" {
  default = yes;
  hosts = "/var/run/rspamd/rspamd-normal.sock";
}
```

/var/log/rspamd/rspamd.log:
```
2018-05-12 16:39:46 #16953(rspamd_proxy) <c87136>; proxy; proxy_accept_socket: accepted milter connection from /var/run/rspamd/rspamd-proxy.sock port 0
2018-05-12 16:39:46 #16953(rspamd_proxy) <c87136>; milter; rspamd_milter_process_command: got connection from 185.5.136.88:33014
2018-05-12 16:39:46 #16953(rspamd_proxy) rspamd_inet_address_connect: connect unix:/var/run/rspamd/rspamd-normal.sock failed: 22, 'Invalid argument'
2018-05-12 16:39:46 #16953(rspamd_proxy) <c87136>; proxy; proxy_send_master_message: cannot connect upstream: default(/var/run/rspamd/rspamd-normal.sock)
2018-05-12 16:39:46 #16953(rspamd_proxy) rspamd_inet_address_connect: connect unix:/var/run/rspamd/rspamd-normal.sock failed: 22, 'Invalid argument'
2018-05-12 16:39:46 #16953(rspamd_proxy) <c87136>; proxy; proxy_send_master_message: cannot connect upstream: default(/var/run/rspamd/rspamd-normal.sock)
2018-05-12 16:39:46 #16953(rspamd_proxy) rspamd_inet_address_connect: connect unix:/var/run/rspamd/rspamd-normal.sock failed: 22, 'Invalid argument'
2018-05-12 16:39:46 #16953(rspamd_proxy) <c87136>; proxy; proxy_send_master_message: cannot connect upstream: default(/var/run/rspamd/rspamd-normal.sock)
2018-05-12 16:39:46 #16953(rspamd_proxy) rspamd_inet_address_connect: connect unix:/var/run/rspamd/rspamd-normal.sock failed: 22, 'Invalid argument'
2018-05-12 16:39:46 #16953(rspamd_proxy) <c87136>; proxy; proxy_send_master_message: cannot connect upstream: default(/var/run/rspamd/rspamd-normal.sock)
2018-05-12 16:39:46 #16953(rspamd_proxy) rspamd_inet_address_connect: connect unix:/var/run/rspamd/rspamd-normal.sock failed: 22, 'Invalid argument'
2018-05-12 16:39:46 #16953(rspamd_proxy) <c87136>; proxy; proxy_send_master_message: cannot connect upstream: default(/var/run/rspamd/rspamd-normal.sock)
2018-05-12 16:39:46 #16953(rspamd_proxy) rspamd_inet_address_connect: connect unix:/var/run/rspamd/rspamd-normal.sock failed: 22, 'Invalid argument'
2018-05-12 16:39:46 #16953(rspamd_proxy) <c87136>; proxy; proxy_send_master_message: cannot connect upstream: default(/var/run/rspamd/rspamd-normal.sock)
2018-05-12 16:39:46 #16953(rspamd_proxy) <c87136>; proxy; proxy_send_master_message: cannot connect to upstream, maximum retries has been reached: 6
```

**Closed** 2019-04-01 20:27 UTC
Labels: wontfix

**Comment by rosjat** [comment] 2019-12-01 18:06
just for the record:

 running rspamd 1.7.9  on openBSD 6.4

getting errors related to the unix socket still

`
2019-12-01 18:46:55 #69926(rspamd_proxy) <a3c6a2>; proxy; proxy_send_master_message: cannot connect upstream: default(/var/run/rspamd/rspamd-normal.sock)
2019-12-01 18:46:55 #69926(rspamd_proxy) <a3c6a2>; proxy; proxy_send_master_message: cannot connect upstream: default(/var/run/rspamd/rspamd-normal.sock)
2019-12-01 18:46:55 #69926(rspamd_proxy) <a3c6a2>; proxy; proxy_send_master_message: cannot connect upstream: default(/var/run/rspamd/rspamd-normal.sock)
2019-12-01 18:46:55 #69926(rspamd_proxy) <a3c6a2>; proxy; proxy_send_master_message: cannot connect upstream: default(/var/run/rspamd/rspamd-normal.sock)
2019-12-01 18:46:55 #69926(rspamd_proxy) <a3c6a2>; proxy; proxy_send_master_message: cannot connect upstream: default(/var/run/rspamd/rspamd-normal.sock)
2019-12-01 18:46:55 #69926(rspamd_proxy) logger; file_log_function: Last message repeated 5 times
2019-12-01 18:46:55 #69926(rspamd_proxy) <a3c6a2>; proxy; proxy_send_master_message: cannot connect to upstream, maximum retries has been reached: 6

`
