### ISSUE TITLE
[BUG] Can't make user settings work

### ISSUE THREAD

**Issue by rekcuFniarB** [rspamd/rspamd#3038] opened 2019-09-15 19:24 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Trying to make example [user settings](https://rspamd.com/doc/configuration/settings.html) to work with no luck.

Multiple examples of `local.d/settings.conf` I've tried:

```lua
whitelist_local {
    id = "whitelist_local";
    priority = high;
    authenticated = yes;
    apply {
        subject = "%s [SCORE: %d]";
    }
    #want_spam = yes;
}
```

```lua
whitelist_local {
    id = "whitelist_local";
    priority = high;
    from = "username@myhostname.com";
    apply {
        subject = "%s [SCORE: %d]";
    }
    #want_spam = yes;
}
```

```lua
whitelist_local {
    id = "whitelist_local";
    priority = high;
    from = "@myhostname.com";
    apply {
        subject = "%s [SCORE: %d]";
    }
    #want_spam = yes;
}
```

```lua
whitelist_local {
    id = "whitelist_local";
    priority = high;
    local = yes;
    apply {
        subject = "%s [SCORE: %d]";
    }
    #want_spam = yes;
}
```

```lua
whitelist_local {
    id = "whitelist_local";
    priority = high;
    from = "@gmail.com";
    apply {
        subject = "%s [SCORE: %d]";
    }
    #want_spam = yes;
}
```

For every example I tried to send via `sendmail` from localhost and Thunderbird to myself from remote host, none of them worked as expected.

Sendmail command:

```bash
echo "Subject: Test

Message body" | sendmail username
```

Raw received email source when sent from localhost via `sendmail`:
```eml
Return-Path: <username@myhostname.com>
X-Original-To: username@myhostname.com
Delivered-To: username@myhostname.com
Received: by mail.myhostname.com (Postfix, from userid 1000)
	id 6CE5F410CB; Sun, 15 Sep 2019 22:08:05 +0300 (MSK)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=myhostname.com;
	s=main; t=1568574485; h=from:from:sender:reply-to:subject:subject:date:date:
	 message-id:message-id:to:cc:mime-version:content-type:
	 content-transfer-encoding:in-reply-to:references;
	bh=0YXRg9C5INC/0LjQt9C00LAg0LTQttC40LPRg9GA0LTQsAo=;
	b=0J/Rg9GC0LjQvSDRhdGD0LkuINCd0LDQstCw0LvRjNC90YvQuSDRgtC+0LbQtSDRhdGD0LkuCtCb
        0LjQvdGD0LrRgSDRgNGD0LvQuNGCLgo=

Subject: Test
Message-Id: <20190915190805.6CE5F410CB@mail.myhostname.com>
Date: Sun, 15 Sep 2019 22:08:05 +0300 (MSK)
From: username@myhostname.com (Username)

Message body
```

Processing of outbound mail is enabled (DKIM signing via Rspamd is working).

**Expected behavior**
Subject change to `Subject [SCORE: XX]`

### Versions

1.8.3 and 1.9.4

**Comment by StrathCole** [comment] 2019-09-18 09:33
Just a guess: you missed adding the rewrite subject action. From the docs:

> subject - string value that replaces the message’s subject if the rewrite subject action is applied. Original subject can be included with %s. Message score can be filled using %d extension.

So you'd need something like that or similar, I think:
```
hitelist_local {
    id = "whitelist_local";
    priority = high;
    authenticated = yes;
    apply {
        subject = "%s [SCORE: %d]";
        action {
               "rewrite subject" = 0.1; 
        }
    }
    #want_spam = yes;
}
```

**Comment by rekcuFniarB** [comment] 2019-09-18 13:24
```
apply {
        subject = "%s [SCORE: %d]";
        actions {
               "rewrite subject" = 0.1; 
        }
    }
```
Thanks. This just adds "*** SPAM ***" to the subject, but it's ok in my case, it was used just for debugging. Main goal was to use `want_spam = yes`.

Another problem is I can't make it match local mail:
`authenticated = yes` matches only mail sent from remote client but not from local sendmail.
`local = yes` doesn't too (this is probably OK, because mail from local sendmail doesn't contain any IP).
`from = "@myhostname.com"` works, but this will probably match also fake mails.
What is better rule to match local sender (e.g. sendmail from localhost)?

**Comment by vstakhov** [comment] 2019-09-18 13:27
Guys, GH issue tracker is *NOT* an appropriate place to ask a questions about Rspamd. It's purpose is solely bug reports and/or feature requests tracking. Please use other support channels (listed on https://rspamd.com/support.html) for this type of conversations. I'm closing this ticket as it is obviously not a bug report.

**Closed by vstakhov** 2019-09-18 13:27 UTC
Labels: bug
