### ISSUE TITLE
Support for Ubuntu 20.04/FocalFossa

### ISSUE THREAD

**Issue by jneuhauser** [rspamd/rspamd#3360] opened 2020-05-01 21:56 UTC
Dear dev team,

first of all thanks for this great project.

Can you make a statement when there will be official packages for the new Ubuntu LTS release 20.04/FocalFossa?

Thanks a lot.

**Comment by vstakhov** [comment] 2020-05-04 11:53
Duplicate of #3348

**Closed by vstakhov** 2020-05-04 11:53 UTC
