### ISSUE TITLE
[BUG] Rspamd crashes randomly on access Symbols and rules in Web-UI

### ISSUE THREAD

**Issue by poralix** [rspamd/rspamd#2885] opened 2019-05-04 09:10 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Rspamd crashes randomly on access Symbols and rules in Web-UI. 

```
reason:         rspamd killed by SIGABRT
cmdline:        'rspamd: controller process (localhost:11334)' ''
executable:     /usr/bin/rspamd
package:        rspamd-1.9.2-1
component:      rspamd
```

### Steps to Reproduce

1. Connect to web-UI
2. Go to `Symbols` tabs, clicking on it
3. See no content under title 'Symbols and rules'

Several reloads and/or restart `rspamd` might temporary fix it.

**Expected behavior**

A loaded page with `Symbols and rules` to edit.

### Versions

CentOS Linux release 7.6.1810 (Core)
Rspamd: 1.9.2 Version, rpm: rspamd-1.9.2-1.x86_64

### Additional Information

Reports at Fedora Analysis Framework:

- https://retrace.fedoraproject.org/faf/reports/2544353/

**Comment by vstakhov** [comment] 2019-05-04 09:20
**Checked that there is not already an experimental package or master branch** - have you done that?

**Comment by poralix** [comment] 2019-05-04 09:40
My apologies, I've missed the step. Testing it now, and can say it does not crash. I will keep testing for a day or two and let you know results.

Thank you for your time.

**Comment by daringer** [comment] 2019-05-05 19:06
I can confirm this crash, with same traceback on:
**OS**: ArchLinux
**Version**: 1.9.2 (package manager version: 1.9.2-2)

Seems to be a _permission issue_, can also contribute the solution, at least for my system:

* Looks like the default user used for `rspamd` has been changed by the ArchLinux packagers from `_rspamd` to `rspams`
* rspamd crashes while trying to access `/var/lib/rspamd` as the owner of this directory and underlying tree was changed from `_rspamd` to `rspamd` pretty much yesterday(?) at least this is the last update for the package on ArchLinux [pkg](https://www.archlinux.org/packages/community/x86_64/rspamd/) and here the [hint](https://git.archlinux.org/svntogit/community.git/tree/trunk/rspamd.install?h=packages/rspamd) during upgrade 
* For me it was simply enough to `systemctl restart rspamd` as the auto-restart due to a crash does not a proper systemd-service-file reloading, which then fixes this issue by using `rspamd` instead of `_rspamd` for rspamd processes.

@poralix might be something similar, if not equally easy on fedora.

So @vstakhov, currently this does not look like a `rspamd` bug to me, thus I'll vote for a "reject" :smile:

best

**Comment by vstakhov** [comment] 2019-05-05 19:46
This issue has been fixed in the master branch long ago. It is **not** a permission issue or anything you can workaround.

**Comment by daringer** [comment] 2019-05-05 19:53
weird, because it clearly fixed the issue for me, further I checked before and saw rspamd running as user `_rspamd` and the mentioned directories are owned by `rspamd` user.

1.9.2 is also the most recent release, right? So with 

> fixed in the master branch long ago

you mean more or less than 19 days? 
so this fix is part of the latest release or just inside the repo and not yet released.

However, sorry for any confusion, it fixed the issue for me and also matches with the changes within the ArchLinux package. Still I might also simply see comparable symptoms without the same underlying reasons.

**Comment by poralix** [comment] 2019-05-06 11:33
In my case user and the directory owner match each other:

```
# ps aux | grep spamd
_rspamd  15244 56.0  1.5 311712 60796 ?        Ss   18:26   0:00 rspamd: main process
_rspamd  15245  0.0  1.3 311712 52904 ?        S    18:26   0:00 rspamd: rspamd_proxy process (localhost:11332)
_rspamd  15246  0.0  1.3 313540 54048 ?        S    18:26   0:00 rspamd: controller process (localhost:11334)
_rspamd  15247  0.0  1.3 312760 53756 ?        S    18:26   0:00 rspamd: normal process (localhost:11333)
_rspamd  15248  0.0  1.3 311712 52680 ?        S    18:26   0:00 rspamd: hs_helper process
root     15250  0.0  0.0 112708   984 pts/1    S+   18:26   0:00 grep --color=auto spamd
```
and

```
# ls -lad /var/lib/rspamd
drwxr-xr-x 2 _rspamd _rspamd 12288 May  6 18:26 /var/lib/rspamd
```

I keep testing...

**Comment by poralix** [comment] 2019-05-06 16:13
It has crashed 2 times today:

```
May  6 22:24:43 server rspamd: *** stack smashing detected ***: rspamd: controller process (localhost:11334) terminated
May  6 22:24:43 server abrt-hook-ccpp: Process 15246 (rspamd) of user 984 killed by SIGSEGV - dumping core
```

I have an experimental version from a rpm installed:

```
# md5sum $(which rspamd)
e31d3dc9e4c502f13531c044765383b0  /bin/rspamd

# ls -la $(which rspamd)
-rwxr-xr-x 1 root root 190936 May  4 01:36 /bin/rspamd

# rpm -qa | grep rspamd
rspamd-1.9.3-9.gitc3bb0a9a0.x86_64

# /bin/rspamd --version
Rspamd daemon version 1.9.3

# ps aux | grep rspamd
_rspamd  12675  0.0  1.3 313540 50896 ?        S    22:24   0:00 rspamd: controller process (localhost:11334)
_rspamd  15244  0.0  1.4 311712 55104 ?        Ss   18:26   0:00 rspamd: main process
_rspamd  15245  0.0  1.3 311712 51620 ?        S    18:26   0:00 rspamd: rspamd_proxy process (localhost:11332)
_rspamd  15247  0.0  1.4 314040 56444 ?        S    18:26   0:00 rspamd: normal process (localhost:11333)
_rspamd  15248  0.0  1.2 311712 49192 ?        S    18:26   0:01 rspamd: hs_helper process
root     17917  0.0  0.0 112712   980 pts/0    S+   22:46   0:00 grep --color=auto rspamd

```

What information should I provide?

**Closed** 2019-05-10 10:07 UTC
Labels: bug

**Comment by poralix** [comment] 2019-05-14 09:37
Всеволод, доброго дня!

Поясните, пожалуйста, вы закрыли баг-репорт  из-за недостаточностью информации? Или по какой другой причине?

rspamd всё так же падает:

```
reason:         rspamd killed by SIGABRT
cmdline:        'rspamd: controller process (localhost:11334)' ''
executable:     /usr/bin/rspamd
package:        rspamd-1.9.4-2.git9bd929050
component:      rspamd

abrt_version:   2.1.11
analyzer:       CCpp
architecture:   x86_64
event_log:
global_pid:     11810
kernel:         3.10.0-957.12.1.el7.x86_64
last_occurrence: 1557826346
os_release:     CentOS Linux release 7.6.1810 (Core)
pkg_arch:       x86_64
pkg_epoch:      0
pkg_fingerprint: FFA2 32ED BF21 E25E
pkg_name:       rspamd
pkg_release:    2.git9bd929050
pkg_vendor:     (none)
pkg_version:    1.9.4
runlevel:       N 3
time:           Tue 14 May 2019 04:32:26 PM +07
type:           CCpp
uid:            984
ureports_counter: 1
username:       _rspamd
uuid:           85648c5dee41175626dc688376232f9ae211d41d
```

и после обновления. Детали должны появится по ссылке: https://retrace.fedoraproject.org/faf/reports/bthash/60a31950d9d68534025ea2e2e5da4bbc67d28c69/

С Уважением,
Алексей.

**Comment by poralix** [comment] 2019-05-17 12:42
```
Core was generated by `rspamd: controller process (localhost:11334) '.
Program terminated with signal 11, Segmentation fault.
#0  x86_64_fallback_frame_state (context=0x7ffc02d77ab0, context=0x7ffc02d77ab0, fs=0x7ffc02d77ba0) at ./md-unwind-support.h:58
58        if (*(unsigned char *)(pc+0) == 0x48
(gdb) frame 0
#0  x86_64_fallback_frame_state (context=0x7ffc02d77ab0, context=0x7ffc02d77ab0, fs=0x7ffc02d77ba0) at ./md-unwind-support.h:58
58        if (*(unsigned char *)(pc+0) == 0x48
(gdb) bt
#0  x86_64_fallback_frame_state (context=0x7ffc02d77ab0, context=0x7ffc02d77ab0, fs=0x7ffc02d77ba0) at ./md-unwind-support.h:58
#1  uw_frame_state_for (context=context@entry=0x7ffc02d77ab0, fs=fs@entry=0x7ffc02d77ba0) at ../../../libgcc/unwind-dw2.c:1253
#2  0x00007f9001b55fb9 in _Unwind_Backtrace (trace=0x7f900188cda0 <backtrace_helper>, trace_argument=0x7ffc02d77d60) at ../../../libgcc/unwind.inc:290
#3  0x00007f900188cf16 in backtrace () from /lib64/libc.so.6
#4  0x00007f90017f1d44 in __libc_message () from /lib64/libc.so.6
#5  0x00007f90018909e7 in __fortify_fail () from /lib64/libc.so.6
#6  0x00007f90018909a2 in __stack_chk_fail () from /lib64/libc.so.6
#7  0x00007f9006586646 in rspamd_vprintf_common (func=0x7f90065855b0 <rspamd_printf_append_fstring>, apd=0x7ffc02d78be0, fmt=<optimized out>, args=0x7ffc02d78760)
    at /usr/src/debug/rspamd-1.9.4/src/libutil/printf.c:1117
#8  0x3030303030303030 in ?? ()
#9  0x3030303030303030 in ?? ()
#10 0x3030303030303030 in ?? ()
#11 0x3030303030303030 in ?? ()
#12 0x3030303030303030 in ?? ()
#13 0x3030303030303030 in ?? ()
#14 0x3030303030303030 in ?? ()
#15 0x3030303030303030 in ?? ()
#16 0x3030303030303030 in ?? ()
#17 0x3030303030303030 in ?? ()
#18 0x3531303030303030 in ?? ()
#19 0x3436373635323036 in ?? ()
#20 0x0000393037323630 in ?? ()
#21 0x12168f46fb11ad34 in ?? ()
#22 0x0000000000000000 in ?? ()
(gdb) frame 0
#0  x86_64_fallback_frame_state (context=0x7ffc02d77ab0, context=0x7ffc02d77ab0, fs=0x7ffc02d77ba0) at ./md-unwind-support.h:58
58        if (*(unsigned char *)(pc+0) == 0x48
(gdb) frame 1
#1  uw_frame_state_for (context=context@entry=0x7ffc02d77ab0, fs=fs@entry=0x7ffc02d77ba0) at ../../../libgcc/unwind-dw2.c:1253
1253          return MD_FALLBACK_FRAME_STATE_FOR (context, fs);
(gdb) frame 2
#2  0x00007f9001b55fb9 in _Unwind_Backtrace (trace=0x7f900188cda0 <backtrace_helper>, trace_argument=0x7ffc02d77d60) at ../../../libgcc/unwind.inc:290
290           code = uw_frame_state_for (&context, &fs);
(gdb) frame 3
#3  0x00007f900188cf16 in backtrace () from /lib64/libc.so.6
(gdb) frame 4
#4  0x00007f90017f1d44 in __libc_message () from /lib64/libc.so.6
(gdb) frame 5
#5  0x00007f90018909e7 in __fortify_fail () from /lib64/libc.so.6
(gdb) frame 6
#6  0x00007f90018909a2 in __stack_chk_fail () from /lib64/libc.so.6
(gdb) frame 7
#7  0x00007f9006586646 in rspamd_vprintf_common (func=0x7f90065855b0 <rspamd_printf_append_fstring>, apd=0x7ffc02d78be0, fmt=<optimized out>, args=0x7ffc02d78760)
    at /usr/src/debug/rspamd-1.9.4/src/libutil/printf.c:1117
1117    }
(gdb) frame 8
#8  0x3030303030303030 in ?? ()
(gdb) frame 9
#9  0x3030303030303030 in ?? ()
(gdb)
```
