### ISSUE TITLE
[Feature] Improve rspamc's "cannot connect to localhost" error message

### ISSUE THREAD

**Issue by mconigliaro** [rspamd/rspamd#3328] opened 2020-04-09 19:02 UTC
## Summary

I ran into this today:

    $ rspamc learn_spam sdbox/mailboxes/Junk/dbox-Mails/
    ...
    cannot connect to localhost

I couldn't figure out what was wrong until I ran the above with `strace` and saw a bunch of `EMFILE (Too many open files)` errors. Here's how I fixed it:

    $ ulimit -S -n
    1024
    $ ulimit -S -n unlimited
    $ ulimit -S -n
    1048576

## Motivation

Adding some detail to the generic `cannot connect to localhost` message would facilitate troubleshooting.

**Comment by vstakhov** [comment] 2020-04-09 19:08
What version do you use? Please fill the issue template carefully...

**Comment by mconigliaro** [comment] 2020-04-09 19:14
Sorry, I didn't see anything asking for a version in the feature request template.

    $ rspamd --version
    Rspamd daemon version 2.5

I believe I saw this on 2.4 too, but I only figured out what was going on today.

**Comment by bslavin** [comment] 2020-05-07 17:49
@mconigliaro - THANK YOU. 

Here were my system configs -

Amazon Web Services -  Elasticache - r5.large, machines. The problem I am having. I am trying to train using the https://spamassassin.apache.org/old/publiccorpus/20030228_spam_2.tar.bz2  - I keep getting timeouts on Redis with an error:

Results for file: 01013.c6cf4f54eda63230389baccc02702034 (0.156 seconds)
error = "<20020724164624.B20BB2940B2@xent.com> has been already learned as spam, ignore it";
filename = "01013.c6cf4f54eda63230389baccc02702034";
scan_time = 0.156003;

cannot connect to localhost


Here is a video of the issue - https://www.screencast.com/t/5ikSlgN0MMp

**Comment by vstakhov** [comment] 2020-05-07 19:39
I'm inclined to join `thank you` spree here :)

**Comment by vstakhov** [comment] 2020-05-07 19:59
That should be fixed now.

**Comment by mconigliaro** [comment] 2020-05-07 20:00
Yup, that looks exactly like my issue. Fortunately(?), I spent a few years working at a fairly well known internet company which shall remain nameless where we had a dearth of good logging, so the ops team had to get pretty good with `strace` to have any hope of troubleshoot anything. This was actually an easy one compared to that. 😂😭 Glad I could help!

**Comment by vstakhov** [comment] 2020-05-07 20:00
The problem with FD limit was caused by a descriptors leak BTW. It was introduced as an effrot to fix another issue with epoll_ctl after close but actually it has introduced an FD leak at the same time.

**Comment by vstakhov** [comment] 2020-05-07 20:01
I have also improved the error message btw.

**Comment by vstakhov** [comment] 2020-05-07 20:03
@mconigliaro it seems that all enterprise logging just sucks tbh. I'm always trying to improve Rspamd logging in fact as I know the pain of poor logging introduced by incompetent developers. And I'm sorry for this partcular fuckup in logging that is definitely on my side.

**Comment by mconigliaro** [comment] 2020-05-07 20:05
@vstakhov rspamd rules. Thank you for saving us all from the horrors of amavis and ancient Perl!

**Closed** 2020-07-13 21:15 UTC
Labels: enhancement, wontfix
