### ISSUE TITLE
MIME-Attachment filename encoding

### ISSUE THREAD

**Issue by TazerReloaded** [rspamd/rspamd#2757] opened 2019-02-14 18:24 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):
I wrote a function for custom attachment analysis in rspamd.local.lua. I use `p:get_filename()` to get the filenames of MIME-Parts and compare them with a Regex-Map. I'm not using the Multimap module because i want to add a custom header and log the suspicious extensions (which works very well).
The Problem is, that sometimes the filenames are encoded with RFC 2047 and rspamd does not decode that. I get filenames like: **=?iso-8859-1?q?testfile=2epdf?=**
This makes matching in lua very difficult.

### Expected results:
The filename should always be provided as UTF-8.

### Actual results:
The filename actually is encoded RFC 2047.

### Additional information:
Here is my filter function:
```lua
local extension_whitelist = rspamd_config:add_map({
    type = 'regexp',
    url = 'file:///etc/rspamd/extension_whitelist.map',
    description = 'Allowed attachment file extensions'
})
rspamd_config.SUSPICIOUS_EXTENSION = {
    callback = function(task)
        local result = false -- the end result, true for match
        local parts = task:get_parts() -- get all MIME parts
        -- loop over all parts
        local description = {}
        for _,p in ipairs(parts) do
            if p:is_archive() then
                local fnames = p:get_archive():get_files()
                for _,fn in ipairs(fnames) do
                    if not extension_whitelist:get_key(fn) then
                        result = true
                        table.insert(description, fn)
                    end
                end
            end
            local fn = p:get_filename()
            if fn and not extension_whitelist:get_key(fn) then
                result = true
                table.insert(description, fn)
            end
        end
        if result then
            task:insert_result('SUSPICIOUS_EXTENSION', 0.0, table.concat(description, ', '))
            task:set_rmilter_reply({
                add_headers = {['X-Suspicious-Extension'] = 'Yes'}
            })
        end
        return result
    end,
    score = 1.0,
    description = 'Contains attachment with extension not on whitelist'
}
```

**Comment by vstakhov** [comment] 2019-02-18 11:31
It cannot be. Do you have any concrete message samples - at least the particular relevant Content-Type/Content-Disposition headers?

**Comment by TazerReloaded** [comment] 2019-02-18 12:21
I thought the same, but it happens with a few messages every day.
Here is one of those, my script reports the following:
SUSPICIOUS_EXTENSION (1) [20190218090914.dxf, =?utf-8?q?dxf-datei_flst._1205-65_gmkg._k=c3=b6nigsbrunn.zip?=]
The *.dxf is inside the zip-file, so that part works correctly, but the zip-file itself seems to be still encoded.
Here is the message, with most of the content snipped out for privacy:

```
Subject: =?utf-8?q?_DXF-Datei_Flst._1205/65_Gmkg._K=C3=B6?=
	=?utf-8?q?nigsbrunn?=
[...]
Date: Mon, 18 Feb 2019 09:16:01 +0100
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101
 Thunderbird/52.5.2
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="------------F6BED1B4B33FE276171799AE"
Content-Language: de-DE
X-Suspicious-Extension: Yes
X-Spamd-Bar: -

This is a multi-part message in MIME format.
--------------F6BED1B4B33FE276171799AE
Content-Type: multipart/alternative;
 boundary="------------261598A921A7EDA096B9361F"


--------------261598A921A7EDA096B9361F
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit

Sehr geehrte Damen und Herren,

[...]

Wir bedanken uns für Ihren Auftrag!

Mit freundlichen Grüßen
[...]

--------------261598A921A7EDA096B9361F
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
[...]
  </body>
</html>

--------------261598A921A7EDA096B9361F--

--------------F6BED1B4B33FE276171799AE
Content-Type: application/zip;
 name="=?UTF-8?Q?DXF-Datei_Flst._1205-65_Gmkg._K=c3=b6nigsbrunn.zip?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename*0*=utf-8''%44%58%46%2D%44%61%74%65%69%20%46%6C%73%74%2E%20%31%32;
 filename*1*=%30%35%2D%36%35%20%47%6D%6B%67%2E%20%4B%C3%B6%6E%69%67%73%62;
 filename*2*=%72%75%6E%6E%2E%7A%69%70

UEsDBBQAAAAIACtJUk6QsbO0AW8AAEp8BQASABUAMjAxOTAyMTgwOTA5MTQuZHhmVVQJAAMy
aGpcMmhqXFV4BABSBOgD7b3Jjh3JkSi6F1D/kLh4Cwnoc66PMVzgLUhVkiKqOFwOUksbIkke
[...]
AAgAE2X/RgFs7zVxDQEAPCcBAB4ADQAAAAAAAAAAAKSB/cIFAHdpZGVycnVmc3JlY2h0X3Zl
cmJyYXVjaGVyLnBkZlVUBQADplC7VVV4AABQSwUGAAAAAAQABABJAQAAv9AGAAAA
--------------F6BED1B4B33FE276171799AE--
```

**Comment by vstakhov** [comment] 2019-02-18 12:32
I can confirm I was able to reproduce it, thanks!

**Comment by vstakhov** [comment] 2019-02-18 14:28
The `Content-Type` header seems to be badly formatted indeed. According to https://tools.ietf.org/html/rfc2047#section-5 the `quoted-word` must **NOT** appear there by the following rule:

* An 'encoded-word' MUST NOT appear within a 'quoted-string'.

However, SHINY email clients seem to ignore this rule and decode rfc2047 token in this case.

**Comment by vstakhov** [comment] 2019-02-18 15:11
All should be fixed now.

**Comment by TazerReloaded** [comment] 2019-02-19 09:03
Cool, thank you for the quick response and fix!

**Closed** 2019-02-19 10:42 UTC
Labels: bug
