### ISSUE TITLE
[BUG] SPF record resolving fails

### ISSUE THREAD

**Issue by dupondje** [rspamd/rspamd#4012] opened 2021-12-17 10:19 UTC
**Describe the bug**
#1177402(normal) <d6c8e4>; spf; spf_record_dns_callback: spf error for domain app.sodexo.com: cannot resolve INCLUDE record for sodexo.com: requested record is not found

This while:
```
# dig +short txt sodexo.com
"atlassian-domain-verification=3idnPToVP7rGPxCTI1z05REJP/vOP2HxMJhEYocvj6APp1n7rn2CN9KQFm7wKFBj"
"MS=ms53460658"
"google-site-verification=0FOVtW6yb48AvhIMGFlmTZaGnj7LMI55uiaq3mOrk6U"
"S0O0D66252"
"adobe-idp-site-verification=c0a8c9e6379c63fc7e95c346468c7e4438603f6521891b9381407d567cb6823d"
"pardot786623=a1077916ce6fce115acc5e2230d6c0762bc9469f63d276bcf7a59ccbbee58899"
"access-domain-verification=65b1191db9cca0ab2cf6308770c10caa13048d3e1254865b473045fe31538099"
"\226\128\1579aSMeVoIckTroAWoPATNoPii6bjdBC3wLcycv27636g=\226\128\157"
"v=spf1 ip4:89.107.171.36 a:smtpgate.sodexo.com include:spf-00009201.pphosted.com include:spf.sodexo.com -all"
"atlassian-domain-verification=RTBIoY9v1hEyXeBsklAaIzYhpGNhQYBltxVaUVf0JATQ4lKPfPbLO05uft1CO6Y4"
"MS=ms43823393"
"7OCi8pHTiroOYbKYBEyYJ16Hq8yR1kjQo+gQU1pqEcg="
"google-site-verification=JSijr8pJzaiE4A2oA_KjfMQyQevstwSGXKMxmr24VH4"
"xjmc07g0xqqzj7t069dz9jkpcg0vbsqp"
"_globalsign-domain-verification=6udFke2izwJGu05097QUK0At3vtmQ_OvgzwYH3r2Z5"
"globalsign-domain-verification=d5SZ77hFmfvmvxKXxzLtPmaacCrmDbAmoap8lHnXSR"
"apple-domain-verification=Pgs1gsguPf0bdC8Z"
"/ZlYYlMDIlgVz/7P0yEfohPlCHVydSTb7Vo7dBbFw58nUE2r++c+Sjsw6Nntde+9d9f1Jc15NHsGNEi7o8moNA=="
"_globalsign-domain-verification=TEslDjVK3eyvcluf44P6zCrEIvWO1Bd8uhJtXNCZFd"
```

I guess something goes wrong because there are a lot of other records here.
But still it has a valid SPF record.

### Versions
Happens on rspamd 3.1

**Comment by vstakhov** [comment] 2021-12-17 12:02
It's likely that the record is more than 4096 bytes, to resolve it a DNS resolver must either agree with the recursor about EDNS size (which is typically limited to 4k) or switch to TCP. Rspamd resolver will never switch to TCP - it is just stupid. I am quite frustrated about all these records that have all those `validation` crap. And I'm equally frustrated that SPF designers or those `verification` monkeys could not use a separate service records, such as `_dmarc` or `_acme-challenge`. The former things are good examples of the reasonable design patterns. Probably SPF has appeared to early so it's designers were not aware of the stupid things that people can do with their DNS. But there are no such excuses for big companies like Google, Apple or Atlassian. And Globalsign should clearly learn from Letsencrypt about how to do DNS challenges properly.

In 3.2, Rspamd will recognise truncated records and will set PERMFAIL flag. That's all I can do for now, as I'm not keen to tolerate stupid behaviour in the Internet. And the argument `too big to be blocked` is not valid here.

**Comment by dupondje** [comment] 2021-12-17 12:40
While I agree there is to much crap in the txt record of that domain, it still seems to fit under 4k bytes.
Dig reports only
;; MSG SIZE  rcvd: 1532

So it might be something else goes wrong?
Is there a way to have some more debugging in the resolver?
Or a way to call rdns directly to see what it returns?

**Comment by citrin** [comment] 2021-12-17 13:40
@dupondje are you able to reproduce this issue? `cannot resolve INCLUDE record` indicates problem with domain used in `include:` but includes for `sodexo.com` look fine (at least now).

**Comment by dupondje** [comment] 2021-12-17 13:41
@citrin : yes it happens all the time

**Comment by citrin** [comment] 2021-12-17 14:08
1. In this case it should be possible to collect traffic dump (`tcpdump` with flags `-s0 -vv`). It may help to understand the issue.
2. Is `rspamadm dnstool` working in your environment (with DNS server you use)? It works for me:
```
$ rspamadm dnstool spf -d sodexo.com -i 89.107.171.56
Policy: pass
Network: 89.107.171.56/32
Original: ip4:89.107.171.56
```

**Comment by dupondje** [comment] 2021-12-17 16:13
After some more debugging the root cause was found :)
Even dig +notcp does tcp lookups if needed it seems :(

As the recursor is pdns_recursor, it limits UDP responses to 1232.
So that causes pdns_recursor to return nothing over UDP, as the response would be to large.

You can adjust this by setting the udp-truncation-threshold value.
https://docs.powerdns.com/recursor/settings.html#udp-truncation-threshold

This can raise the limit, but after all it should failover to TCP resolving. (But currently/will never be implemented in rspamd)

**Comment by citrin** [comment] 2021-12-17 16:32
Rising `udp-truncation-threshold` to 4096 should fix SPF resolving for this and many other domains.

TCP fallback would fix the rest of them (or this domain without changing DNS recursor settings), but it would be very difficult to fit into existing Rspamd architecture and as Vsevolod noted above he has not plans for this.

**Comment by vstakhov** [comment] 2021-12-17 16:36
@citrin, TBH, it is easier and more interesting to implement DNS over HTTP(s) support in Rspamd. 

As we have discussed privately, I'm going to increase EDNS size to 8K as a short-term fix, add the documentation about DNS setup to mention EDNS limit but in general it might be an interesting project to do DoH fallback for `heavy` requests.

**Comment by vstakhov** [comment] 2022-01-06 16:27
It seems that TCP fallback is working and functional now.

**Closed by vstakhov** 2022-01-06 16:27 UTC
Labels: bug
