### ISSUE TITLE
[BUG] IPv6 ASN not resolved correctly

### ISSUE THREAD

**Issue by ohader** [rspamd/rspamd#2978] opened 2019-07-14 20:50 UTC
**Describe the bug**

ASN is not resolved correctly for IPv6 sources.

### Steps to Reproduce

* Sender using IPv6 address (e.g. `2003:f0:93d3:39fc:211::0`) handing in mail to rspamd
* ASN module resolved to `ASN (0) [asn:12552, ipnet:2000::/6, country:SE]`
* (`2000::/6` is wrong in this case, resulting in wrong autonomous system and country code)

**Expected behavior**

* correct network would have been `2003::/19` (using `whois`)
* expected`ASN (0) [asn:3320, ipnet:2003::/19, country:DE]`

### Versions

* Rspamd daemon version 1.9.4
* Debian GNU/Linux 9.9 (stretch)

### Additional Information

ASN module configuration is unchanged using package defaults - very similar to https://rspamd.com/doc/modules/asn.html

**Comment by vstakhov** [comment] 2019-07-16 09:05
It is caused by some change of bgp dumps provided by ripe. `NET::MRT` module cannot parse some structures. It should be fixed by https://github.com/rspamd/rspamd/commit/8238a25077f93f027119defe5dd010d3284e85de The updates zones will soon be propagated.

**Closed** 2019-08-28 11:43 UTC
Labels: bug
