### ISSUE TITLE
[Feature] Ubuntu Jammy packages ?

### ISSUE THREAD

**Issue by amarc** [rspamd/rspamd#4158] opened 2022-04-24 09:50 UTC
Hello,

what are plans to soon have Ubuntu 22.04 packages available via APT ? I know it's been only 4 days since 22.04 is released but it's LTS and some of us are waiting for package to do new setups rather than do it on 20.04

Best, A.

**Comment by Qadisha** [comment] 2022-05-22 08:42
agree with @amarc  we really need to move away from v2.7 and get latest from rspamd repo.

Thanks

**Comment by Dacesilian** [comment] 2022-07-05 05:24
Package is still missing. Can you please take a look at it?

**Comment by uschindler** [comment] 2022-07-20 09:20
FYI, it looks like the "focal" packages work perfectly fine on 22.04. So just have focal in `/etc/apt/sources.list.d`.

**Comment by beamsi** [comment] 2022-07-20 14:28
> FYI, it looks like the "focal" packages work perfectly fine on 22.04. So just have focal in `/etc/apt/sources.list.d`.

at least on my Ubuntu 22 machine it has unmet depencies:
```
The following packages have unmet dependencies:
 rspamd : Depends: libicu66 (>= 66.1-1~) but it is not installable
          Depends: libssl1.1 (>= 1.1.1) but it is not installable
```

**Comment by uschindler** [comment] 2022-07-20 14:38
Hi @beamsi,
I forgot to mention that this was an upgraded 20.04 => 22.04 machine (do-release-upgrade). So yes, the problem is there if you have a fresh install. During the update libicu66 and libssl1.1 were kept installed (as rspamd depends on them), but if you haven't it installed, it fails.
A workaround would be to download the deb files of those missing packages from 20.04 (focal), but that's all a hack.

```
# dpkg -l | egrep '(libicu|libssl)'
ii  libicu55:amd64                        55.1-7ubuntu0.4                                        amd64        International Components for Unicode
ii  libicu66:amd64                        66.1-2ubuntu2.1                                        amd64        International Components for Unicode
ii  libicu70:amd64                        70.1-2                                                 amd64        International Components for Unicode
ii  libssl1.0.0:amd64                     1.0.2n-1ubuntu5.3                                      amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64                       1.1.1l-5myguard5~focal                                 amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl3:amd64                         3.0.2-0ubuntu1.6                                       amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl3:i386                          3.0.2-0ubuntu1.6                                       i386         Secure Sockets Layer toolkit - shared libraries
```

**Comment by vstakhov** [comment] 2022-07-20 21:02
I have built jammy packages for the experimental repo. Please test those if you can. The next stable release `3.3` will deprecate `Xenial` distro and will add packages for `Jammy`.

**Comment by uschindler** [comment] 2022-07-20 21:52
Hi,
I see no packages yet in https://rspamd.com/apt/dists/jammy/main/binary-amd64/

**Comment by uschindler** [comment] 2022-07-20 22:20
It still looks like the above deb file depends on libssl1.1 and libicu66 that has no installation candidate in Ubuntu 22.04

**Comment by vstakhov** [comment] 2022-07-20 22:40
Yes, it seems there is still some issue with the [pool packages](https://rspamd.com/apt/pool/main/r/rspamd/) for Jammy. I will check that tomorrow.

**Comment by windware-ono** [comment] 2022-08-22 04:34
Any progress?

It's been 4 months since Jammy was released and I cannot install rspamd on it. (Unless with the .deb mentioned above.)

**Comment by urmel1960** [comment] 2022-08-28 10:12
I tried to install rspamd on 22.04 from experimental packages as mentioned above by @vstakhov . I do still get 2.7 installed on the machine. 
Is there any solution for this ?
How can rspamd latest build can be installed on 22.04 LTS ?

**Comment by BradKollmyer** [comment] 2022-08-28 19:57
I am getting the latest. Create the file `/etc/apt/sources.list.d/rspamd.list` with the following contents:
```
deb [arch=amd64] http://rspamd.com/apt/ jammy main
deb-src [arch=amd64] http://rspamd.com/apt/ jammy  main
```

The execute:
```
apt update
apt dist-upgrade
```

**Comment by urmel1960** [comment] 2022-08-28 21:25
I tried that before - as already mentioned above - there are still no packeges for jammy asvailable

**Comment by urmel1960** [comment] 2022-08-30 13:19
> I have built jammy packages for the experimental repo. Please test those if you can. The next stable release `3.3` will deprecate `Xenial` distro and will add packages for `Jammy`.

@vstakhov 

Do you have any idea when `3.3`  will be released  or do you have any workaround for the meantime for people trying to let rspamd run on jammy ?

Thanks in advance for your response

**Comment by unixtastic** [comment] 2022-08-31 20:52
I'd also very much like a stable release for jammy. I can't find nightly builds for jammy as the release file in zero bytes.

Any ETA?

**Comment by uschindler** [comment] 2022-09-14 16:19
@aeigus this was always the case, rapsmd was also in Ubuntu 20.04. The problem is another one: The jammy packaged version by Ubuntu is plain outdated: https://packages.ubuntu.com/jammy/rspamd (version 2.7)

**Comment by aeigus** [comment] 2022-09-14 16:21
@uschindler Indeed, my apologies.

**Comment by uschindler** [comment] 2022-09-14 16:21
The newest version is also available in kinetic: https://packages.ubuntu.com/kinetic/rspamd

For a spam checker like rspamd you need to be uptodate. Using stone-aged LTS releases is not a good idea.

**Comment by chr4** [comment] 2022-09-15 11:08
Manually installing `kinetic` packages seems to work (leaves you without automatic apt updates, though):

```bash
wget http://de.archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu71_71.1-3_amd64.deb
wget http://de.archive.ubuntu.com/ubuntu/pool/universe/r/rspamd/rspamd_3.2-3_amd64.deb

dpkg -i libicu71_71.1-3_amd64.deb
dpkg -i rspamd_3.2-3_amd64.deb
```

**Comment by urmel1960** [comment] 2022-09-18 10:37
@chr4 
That worked ! Thanks a lot for that advice and your input

Hopefully the issue metioned above will be generally solved soon  so that we do not need to go with work-arounds ...

**Comment by urmel1960** [comment] 2022-10-02 15:18
v3.3 is released now. 
Although  it was said thet the next stable release 3.3 will deprecate Xenial distro and there will be packages for Jammy there is nothing to find in the docs and there are still no packages available for Jammy.

**Comment by vstakhov** [comment] 2022-10-02 16:47
It seems there is a bug in rerepro that prevents zstd compressed debian packages to be processed into a repo.

**Comment by vstakhov** [comment] 2022-10-02 17:24
It should be fixed now...

**Comment by uschindler** [comment] 2022-10-02 18:21
Seems to work. Jammy now finds the package.

**Comment by chr4** [comment] 2022-10-02 19:53
Can confirm. Packages installed manually from [kinetic](https://github.com/rspamd/rspamd/issues/4158#issuecomment-1247950782) are upgraded seemlessly, too!

Thanks 👍🏻

**Comment by urmel1960** [comment] 2022-10-03 07:13
Thanks - The packages are there now. 

But when I install rspamd on Jammy and try to open the webgui I do get 

`Module loading error: scripterror, module: jquery`

**Comment by uschindler** [comment] 2022-10-03 07:52
> Thanks - The packages are there now.
> 
> But when I install rspamd on Jammy and try to open the webgui I do get
> 
> `Module loading error: scripterror, module: jquery` and then `Module loading error: timeout, module: stickytabs,d3pie,d3evolution,footable,bootstrap`

Did you do Shift + Reload? Otherwise web browser won't reload all files.

**Comment by vstakhov** [comment] 2022-10-03 07:54
@moisseev does it worth to mention that in the migration notes?

**Comment by urmel1960** [comment] 2022-10-03 08:13
> Did you do Shift + Reload? Otherwise web browser won't reload all files.

That was the trick - thanks a lot

**Comment by PHPGangsta** [comment] 2022-10-03 08:26
If there are such cache problems, you should use cache-breakers. Something like

scripts.js?v=1

Every time you change something in the file, you increase this version parameter.
Alternatively you automatically (during a build) add a version parameter which is the git commit hash for example, or the rspamd version string.

If you do this for all .js and .css files, you will never have browser cache problems again.

**Comment by foxpalace** [comment] 2022-10-21 15:25
can someone update https://rspamd.com/downloads.html - I'm still unsure about updating without official documentation

**Comment by urmel1960** [comment] 2022-10-21 16:13
made just a [PR](https://github.com/rspamd/rspamd.com/pull/579#issue-1418550850) for rspamd.com 

I recently updated from 3.2 on 20.04 LTS to 3.3 on 22.04 LTS. Went without serious problems. Just don't forget to clear your browser cache (CTRL-F5) after updating if you experience problems with your web-gui and maybe you need to look here as well #4289

**Closed** 2024-05-16 13:20 UTC
Labels: enhancement
