### ISSUE TITLE
Compilation of 1.7.4 fails on arm7l/aarch64/ppc64le platforms

### ISSUE THREAD

**Issue by pief** [rspamd/rspamd#2226] opened 2018-05-06 14:42 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.4

### Operation system, CPU, memory and environment:
Open Build Service with various targets

### Description (Please provide a descriptive summary of the issue):
i586 and x86_64 compile successfully, arm7l, aarch64 and ppc64le don't

### Compile errors (if any):
From https://build.opensuse.org/build/home:pfhllnts:branches:server:mail/openSUSE_Factory_ARM/armv7l/rspamd/_log:
```
In file included from /usr/lib/glib-2.0/include/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /home/abuild/rpmbuild/BUILD/rspamd-1.7.4/build/src/config.h:301,
                 from /home/abuild/rpmbuild/BUILD/rspamd-1.7.4/src/libcryptobox/cryptobox.c:22:
/home/abuild/rpmbuild/BUILD/rspamd-1.7.4/src/libcryptobox/cryptobox.c: At top level:
/usr/include/glib-2.0/glib/gmacros.h:241:53: error: size of array '_GStaticAssertCompileTimeAssertion_1' is negative
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                     ^
/usr/include/glib-2.0/glib/gmacros.h:238:47: note: in definition of macro 'G_PASTE_ARGS'
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:241:44: note: in expansion of macro 'G_PASTE'
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                            ^~~~~~~
/home/abuild/rpmbuild/BUILD/rspamd-1.7.4/src/libcryptobox/cryptobox.c:1480:1: note: in expansion of macro 'G_STATIC_ASSERT'
 G_STATIC_ASSERT (sizeof (t1ha_context_t) ==
 ^~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/rspamd-server.dir/build.make:116: src/CMakeFiles/rspamd-server.dir/libcryptobox/cryptobox.c.o] Error 1
make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/rspamd-1.7.4/build'
```

**Comment by vstakhov** [comment] 2018-05-06 14:49
I don't have access to any of these platforms, so they are not supported by 
Rspamd.

**Comment by pief** [comment] 2018-05-06 18:40
armv7l is used e.g. by the Raspberry Pi and I think it would be cool to keep supporting this as there are many other users using rspamd on their home mail server.

I think that the assertion in ``src/libcryptobox/cryptobox.c``

```
G_STATIC_ASSERT (sizeof (t1ha_context_t) ==
                sizeof (rspamd_cryptobox_fast_hash_state_t));
```

is wrong: ``rspamd_cryptobox_fast_hash_state_t`` is defined with ``RSPAMD_ALIGNED(32)`` whereas ``t1ha_context_t`` in ``contrib/t1ha/t1ha.h`` has ``T1HA_ALIGN_PREFIX`` which is only defined if ``__ia32__`` is defined (which is apparantly only the case on "Stratos VOS").

So I think that ``t1ha_context_t`` should be always 32-bit aligned as well?

Also I was wondering if there is a reason why you didn't just ``typedef t1ha_context_t rspamd_cryptobox_fast_hash_state_t``?

**Comment by vstakhov** [comment] 2018-05-07 07:41
Can you confirm that the issue is fixed if `t1ha_context_t` will be unconditionally`RSPAMD_ALIGNED(32)`?

**Comment by mattreeve** [comment] 2018-05-08 16:36
This looks like a duplicate of #2214 that I logged a few days ago.

I tried building it with this hack of a modification:

diff --git a/contrib/t1ha/t1ha.h b/contrib/t1ha/t1ha.h
index 30c408c87..3005de9c1 100644
--- a/contrib/t1ha/t1ha.h
+++ b/contrib/t1ha/t1ha.h
@@ -229,6 +229,7 @@
 #else
 #define T1HA_ALIGN_SUFFIX
 #endif /* GCC x86 */
+#define T1HA_ALIGN_SUFFIX RSPAMD_ALIGNED(32)

 #ifdef __cplusplus
 extern "C" {

This now builds and runs successfully on my Odroid XU4. Of course, I get warnings about T1HA_ALIGN_SUFFIX being redefined.

**Closed** 2019-03-11 17:00 UTC
