### ISSUE TITLE
[BUG] rspamd v1.94 antivirus module against Sophos Linux

### ISSUE THREAD

**Issue by gunsuka** [rspamd/rspamd#3103] opened 2019-10-18 12:35 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When rspamd submits messages to Sophos Linux not all viruses are detected.  We are using Sophos through the rspamd antivirus module.  The setup does detect _some_ viruses but we are seeing hundreds of .doc files within messages that are not detected.

If we upload the message to VirusTotal, it is detected as Ma/DocDL-K by Sophos
https://www.virustotal.com/gui/file/156b76218f17a03df7d6946174096a7780955c09612117767d356fe6c69e487c/detection

If we put the raw doc file on disk and scan it from the Sophos AV scanner (the 
same install rspamd is using) it gets detected, telling us the engine and the definitions are capable to detecting the virus.

We have tested with various options in local.d/antivirus.conf, specifically testing with

    scan_mime_parts = true;
    scan_text_mine = true;
    scan_image_mime = false;

It does not matter if we have none of those enabled, or scan_mime_parts etc. under no combination can we get the scanner to detect the virus.

![rspamc_result](https://user-images.githubusercontent.com/13393784/67093244-c1a1fe00-f1e3-11e9-94e8-204f379692b0.gif)

I would assume scan_mime_parts = true; would be the best option so Sophos does not have to figure out how to deconstruct the message.

### Steps to Reproduce

1. Use the sample message 1030452.eml, which contains a .doc virus and pass it through rspamd.

2) Use the attached antivirus.conf (attached at .txt to make git happy)

Attached is debug.txt, which we obtained by enabling debugging on process sophos.  The capture of the logs shows two different scans of the test email, one with no options and one with scan_mime_parts = true;

**Expected behavior**
We would expect rspamd to get a reply back from the AV scanner that a virus was detected in the message.

### Versions

Rspamd daemon version 1.9.4
Debian GNU/Linux 9.11

SAVScan virus detection utility
Version 5.63.0 [Linux/AMD64]
Virus data version 5.68, September 2019
Includes detection for 41978407 viruses, Trojans and worms

Sophos Anti-Virus       = 9.16.0
Build Revision          = 2821170
Threat detection engine = 3.77.1
Threat data             = 5.68
Threat count            = 41978407
Threat data release     = Tue 24 Sep 2019 12:00:00 AM
Last update             = Fri 18 Oct 2019 08:27:21 AM UTC

### Additional Information

Configure sophos AV scanner, using antivirus module.  

[1030452.zip](https://github.com/rspamd/rspamd/files/3743814/1030452.zip)

[antivirus.conf.txt](https://github.com/rspamd/rspamd/files/3743856/antivirus.conf.txt)

[debug.txt](https://github.com/rspamd/rspamd/files/3743822/debug.txt)

**Comment by vstakhov** [comment] 2019-10-18 12:44
Duplicate of #3097.

**Closed by vstakhov** 2019-10-18 12:44 UTC
Labels: bug

**Comment by gunsuka** [comment] 2019-10-18 12:51
This looks nothing like #3097 

The item being reported here is from 1.94 and there is no timeout occurring, the scan against Sophos looks like it is running but Sophos is not reporting any virus when there is a virus that Sophos can detect when not being passed the file from rspamd.

**Comment by vstakhov** [comment] 2019-10-18 13:02
The source of the error is the same.

**Comment by whataboutpereira** [comment] 2019-10-18 13:21
It works now. I wonder why it needs to retry every write though.

```
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: want write 2 io vectors of 2
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: got temporary failure, retry write
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_plan_handler_event: plan new write
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_handler: processed TCP event: 2
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: want write 2 io vectors of 2
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: written 521280 bytes: 5298232/6253023
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: want write 2 io vectors of 2
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: got temporary failure, retry write
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_plan_handler_event: plan new write
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_handler: processed TCP event: 2
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: want write 2 io vectors of 2
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: written 521280 bytes: 5819512/6253023
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: want write 2 io vectors of 2
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: written 65160 bytes: 5884672/6253023
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: want write 2 io vectors of 2
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: got temporary failure, retry write
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_plan_handler_event: plan new write
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_handler: processed TCP event: 2
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: want write 2 io vectors of 2
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: written 368351 bytes: 6253023/6253023
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_write_helper: finishing TCP write, calling TCP handler
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_shift_handler: switch from write handler
2019-10-18 16:19:17 #80200(normal) <109480>; lua_tcp; lua_tcp_plan_handler_event: plan new read
2019-10-18 16:19:18 #80200(normal) <109480>; lua_tcp; lua_tcp_handler: processed TCP event: 1
2019-10-18 16:19:18 #80200(normal) <109480>; lua_tcp; lua_tcp_process_read_handler: found TCP stop pattern
2019-10-18 16:19:18 #80200(normal) <0f5343>; clamav; clamav.lua:127: clamav: got reply: stream: OK
2019-10-18 16:19:18 #80200(normal) <0f5343>; clamav; clamav.lua:135: clamav: message or mime_part is clean
2019-10-18 16:19:18 #80200(normal) <109480>; lua_tcp; lua_tcp_shift_handler: switch from read handler
2019-10-18 16:19:18 #80200(normal) <109480>; lua_tcp; lua_tcp_plan_handler_event: no handlers left, finish session
2019-10-18 16:19:18 #80200(normal) <109480>; lua_tcp; lua_tcp_fin: finishing TCP async connection
2019-10-18 16:19:18 #80200(normal) <0f5343>; clamav; common.lua:275: clamav: saved cached result for rs_clamav_811c022d163e01889efcd1c060b76f94: OK - score 1 - ttl 3600
```

**Comment by vstakhov** [comment] 2019-10-18 13:22
Let's say because it is intended so.

**Comment by whataboutpereira** [comment] 2019-10-18 13:23
Hah! Okay. So it's normal in a way. :)

**Comment by whataboutpereira** [comment] 2019-10-18 13:24
1 more issue down. Only ARC failures left here. :)
