### ISSUE TITLE
Failed to open statefile: /var/lib/rspamd/dmarc_reports_last_sent

### ISSUE THREAD

**Issue by PHPGangsta** [rspamd/rspamd#2465] opened 2018-09-06 14:47 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [x] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.9

### Operation system, CPU:
Ubuntu 16.04.5

### Description (Please provide a descriptive summary of the issue):
I have activated dmarc reporting. See configuration below.

I see that reports are generated and sent (because of overridden email address: to me), which works fine, I receive them (all of them have the Sender Displayname "Rspamd", which could be improved, I would like to have "domain.de DMARC report" or something like that):

```
2018-09-06 12:54:49 #19644(controller) <>; lua; dmarc.lua:895: sending report for mail.xing.com <>
2018-09-06 12:54:49 #19644(controller) <>; lua; dmarc.lua:895: sending report for corp.eastlink.ca <>
2018-09-06 12:54:49 #19644(controller) <>; lua; dmarc.lua:895: sending report for reply.ebay.de <>
2018-09-06 12:54:49 #19644(controller) <>; lua; dmarc.lua:895: sending report for arf.mail.yahoo.com <>
```

BUT: I see these errors in the logfile:

```
2018-09-06 15:00:11 #7055(controller) lua; dmarc.lua:1177: Failed to open statefile: /var/lib/rspamd/dmarc_reports_last_sent: No such file or directory
2018-08-31 12:54:49 #19644(controller) lua; dmarc.lua:1177: Failed to open statefile: /var/lib/rspamd/dmarc_reports_last_sent: No such file or directory
```

In /var/lib/rspamd there is no file "dmarc_reports_last_sent" (but other files like .map, .sock, .ucl, .cache, .hsmp):
```
ls -al /var/lib/rspamd/dmarc_reports_last_sent
ls: cannot access '/var/lib/rspamd/dmarc_reports_last_sent': No such file or directory
```

### Configuration (e.g. `rspamadm configdump module`):
```
*** Section dmarc ***
report_settings {
    domain = "domain.de";
    email = "dmarc-support@dmarc.domain.de";
    smtp = "host.domain.de";
    org_name = "domain.de GmbH";
    override_address = "email@domain.net";
}
reporting = true;
send_reports = true;

*** End of section dmarc ***
```

**Comment by gitlarssondk** [comment] 2018-10-27 12:47
Just a comment on you first question.

If you like to change the sender name, please use the following in your reports_settings section:
`from_name = "domain.de DMARC report`

**Comment by gitlarssondk** [comment] 2018-10-27 12:50
This might be a duplicate of #2101

**Closed** 2019-04-01 18:27 UTC
Labels: wontfix
