### ISSUE TITLE
[BUG] 2.0-13.gitb7dbb7d1c does not start on CentOS 7

### ISSUE THREAD

**Issue by gralex54** [rspamd/rspamd#2945] opened 2019-06-27 05:09 UTC
Hello Vsevolod,

The version 2.0-13.gitb7dbb7d1c does not start on CentOS 7

Error: `rspamd killed by SIGSEGV`

Details:

- reason:         rspamd killed by SIGSEGV
- cmdline:        /usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f
- executable:     /usr/bin/rspamd
- package:        rspamd-2.0-13.gitb7dbb7d1c
- component:      rspamd
- kernel:         3.10.0-957.21.3.el7.x86_64
- os_release:     CentOS Linux release 7.6.1810 (Core)
- pkg_arch:       x86_64
- pkg_name:       rspamd
- pkg_release:    13.gitb7dbb7d1c

Backtrace:

```
Core was generated by `/usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f'.
Program terminated with signal 11, Segmentation fault.
#0  init_ab (y=y@entry=0, x=x@entry=3735927486, s=s@entry=0x7fb07edc1448) at /usr/src/debug/rspamd-2.0/contrib/t1ha/t1ha2.c:49
49        s->n.a = x;
(gdb) bt
#0  init_ab (y=y@entry=0, x=x@entry=3735927486, s=s@entry=0x7fb07edc1448) at /usr/src/debug/rspamd-2.0/contrib/t1ha/t1ha2.c:49
#1  t1ha2_init (ctx=ctx@entry=0x7fb07edc1448, seed_x=seed_x@entry=3735927486, seed_y=seed_y@entry=0) at /usr/src/debug/rspamd-2.0/contrib/t1ha/t1ha2.c:269
#2  0x00007fb08e10a54e in rspamd_cryptobox_fast_hash_init (st=st@entry=0x7fb07edc1448, seed=seed@entry=3735927486) at /usr/src/debug/rspamd-2.0/src/libcryptobox/cryptobox.c:1512
#3  0x00007fb08e145fc3 in rspamd_map_helper_new_radix (map=<optimized out>) at /usr/src/debug/rspamd-2.0/src/libutil/map_helpers.c:701
#4  0x00007fb08e19c6b2 in rspamd_config_radix_from_ucl (cfg=cfg@entry=0x7fb0881e9c00, obj=0x7fb0883092c0, description=description@entry=0x7fb08ea08cb5 "Local addresses",
    target=0x7fb08edb7950 <local_addrs>, err=err@entry=0x0) at /usr/src/debug/rspamd-2.0/src/libserver/cfg_utils.c:2197
#5  0x00007fb08e15c10b in rspamd_config_libs (ctx=0x7fb08820b060, cfg=cfg@entry=0x7fb0881e9c00) at /usr/src/debug/rspamd-2.0/src/libutil/util.c:2246
#6  0x00007fb08e19a914 in rspamd_config_post_load (cfg=cfg@entry=0x7fb0881e9c00,
    opts=opts@entry=(RSPAMD_CONFIG_INIT_URL | RSPAMD_CONFIG_INIT_LIBS | RSPAMD_CONFIG_INIT_SYMCACHE | RSPAMD_CONFIG_INIT_VALIDATE | RSPAMD_CONFIG_INIT_PRELOAD_MAPS | RSPAMD_CONFIG_INIT_POST_LOAD_LUA)) at /usr/src/debug/rspamd-2.0/src/libserver/cfg_utils.c:845
#7  0x00000000004169a6 in load_rspamd_config (rspamd_main=0x7fb0881f3000, cfg=0x7fb0881e9c00, init_modules=1,
    opts=(RSPAMD_CONFIG_INIT_URL | RSPAMD_CONFIG_INIT_LIBS | RSPAMD_CONFIG_INIT_SYMCACHE | RSPAMD_CONFIG_INIT_VALIDATE | RSPAMD_CONFIG_INIT_PRELOAD_MAPS | RSPAMD_CONFIG_INIT_POST_LOAD_LUA), reload=0) at /usr/src/debug/rspamd-2.0/src/rspamd.c:911
#8  0x000000000040b34b in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /usr/src/debug/rspamd-2.0/src/rspamd.c:1278
(gdb) frame 0
#0  init_ab (y=y@entry=0, x=x@entry=3735927486, s=s@entry=0x7fb07edc1448) at /usr/src/debug/rspamd-2.0/contrib/t1ha/t1ha2.c:49
49        s->n.a = x;
(gdb) frame 1
#1  t1ha2_init (ctx=ctx@entry=0x7fb07edc1448, seed_x=seed_x@entry=3735927486, seed_y=seed_y@entry=0) at /usr/src/debug/rspamd-2.0/contrib/t1ha/t1ha2.c:269
269       init_ab(&ctx->state, seed_x, seed_y);
(gdb) frame 2
#2  0x00007fb08e10a54e in rspamd_cryptobox_fast_hash_init (st=st@entry=0x7fb07edc1448, seed=seed@entry=3735927486) at /usr/src/debug/rspamd-2.0/src/libcryptobox/cryptobox.c:1512
1512            t1ha2_init (rst, seed, 0);
(gdb) frame 3
#3  0x00007fb08e145fc3 in rspamd_map_helper_new_radix (map=<optimized out>) at /usr/src/debug/rspamd-2.0/src/libutil/map_helpers.c:701
701             rspamd_cryptobox_fast_hash_init (&r->hst, map_hash_seed);
(gdb) frame 4
#4  0x00007fb08e19c6b2 in rspamd_config_radix_from_ucl (cfg=cfg@entry=0x7fb0881e9c00, obj=0x7fb0883092c0, description=description@entry=0x7fb08ea08cb5 "Local addresses",
    target=0x7fb08edb7950 <local_addrs>, err=err@entry=0x0) at /usr/src/debug/rspamd-2.0/src/libserver/cfg_utils.c:2197
2197                                            *target = rspamd_map_helper_new_radix (NULL);
(gdb) frame 5
#5  0x00007fb08e15c10b in rspamd_config_libs (ctx=0x7fb08820b060, cfg=cfg@entry=0x7fb0881e9c00) at /usr/src/debug/rspamd-2.0/src/libutil/util.c:2246
2246                            rspamd_config_radix_from_ucl (cfg, cfg->local_addrs,
(gdb) frame 6
#6  0x00007fb08e19a914 in rspamd_config_post_load (cfg=cfg@entry=0x7fb0881e9c00,
    opts=opts@entry=(RSPAMD_CONFIG_INIT_URL | RSPAMD_CONFIG_INIT_LIBS | RSPAMD_CONFIG_INIT_SYMCACHE | RSPAMD_CONFIG_INIT_VALIDATE | RSPAMD_CONFIG_INIT_PRELOAD_MAPS | RSPAMD_CONFIG_INIT_POST_LOAD_LUA)) at /usr/src/debug/rspamd-2.0/src/libserver/cfg_utils.c:845
845                     rspamd_config_libs (cfg->libs_ctx, cfg);
(gdb) frame 7
#7  0x00000000004169a6 in load_rspamd_config (rspamd_main=0x7fb0881f3000, cfg=0x7fb0881e9c00, init_modules=1,
    opts=(RSPAMD_CONFIG_INIT_URL | RSPAMD_CONFIG_INIT_LIBS | RSPAMD_CONFIG_INIT_SYMCACHE | RSPAMD_CONFIG_INIT_VALIDATE | RSPAMD_CONFIG_INIT_PRELOAD_MAPS | RSPAMD_CONFIG_INIT_POST_LOAD_LUA), reload=0) at /usr/src/debug/rspamd-2.0/src/rspamd.c:911
911             rspamd_config_post_load (cfg, opts);
(gdb) frame 8
#8  0x000000000040b34b in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /usr/src/debug/rspamd-2.0/src/rspamd.c:1278
1278            if (!load_rspamd_config (rspamd_main, rspamd_main->cfg, TRUE,
(gdb)

```

How can I fix it?

Regards,
Alex.

**Comment by moisseev** [comment] 2019-06-27 05:32
```cxx
# rspamd -v
Rspamd daemon version 2.0-git.b7dbb7d
# uname -msv
FreeBSD FreeBSD 12.0-RELEASE-p4 GENERIC  amd64
# lldb `which rspamd` -c /coreland/rspamd-2.0.core
(lldb) target create "/usr/local/bin/rspamd" --core "/coreland/rspamd-2.0.core"
Core file '/coreland/rspamd-2.0.core' (x86_64) was loaded.
(lldb) bt all
* thread #1, name = 'rspamd-2.0', stop reason = signal SIGBUS
  * frame #0: 0x000000080063df00 librspamd-server.so`t1ha2_init(ctx=0x00000008042e6848, seed_x=<unavailable>, seed_y=<unavailable>) at t1ha2.c:272
    frame #1: 0x000000080037da84 librspamd-server.so`rspamd_cryptobox_fast_hash_init(st=0x00000008042e6848, seed=3735927486) at cryptobox.c:1512
    frame #2: 0x00000008003e3745 librspamd-server.so`rspamd_map_helper_new_radix(map=0x0000000000000000) at map_helpers.c:701
    frame #3: 0x0000000800468877 librspamd-server.so`rspamd_config_radix_from_ucl(cfg=0x0000000801f0ec00, obj=0x0000000801fd0f00, description="", target=0x00000008006825e8, err=0x0000000000000000) at cfg_utils.c:2197
    frame #4: 0x0000000800406eaa librspamd-server.so`rspamd_config_libs(ctx=0x0000000801efb4a0, cfg=0x0000000801f0ec00) at util.c:2246
    frame #5: 0x00000008004625fe librspamd-server.so`rspamd_config_post_load(cfg=0x0000000801f0ec00, opts=111) at cfg_utils.c:845
    frame #6: 0x0000000000222878 rspamd`load_rspamd_config(rspamd_main=0x0000000801f18000, cfg=0x0000000801f0ec00, init_modules=1, opts=111, reload=0) at rspamd.c:911
    frame #7: 0x000000000022125c rspamd`main(argc=1, argv=0x00007fffffffeb98, env=0x00007fffffffebd8) at rspamd.c:1278
    frame #8: 0x000000000021111b rspamd`_start(ap=<unavailable>, cleanup=<unavailable>) at crt1.c:76
```

**Comment by moisseev** [comment] 2019-06-27 05:53
Never mind. That crash on FreeBSD was caused by leftover rspamd processes.

**Comment by int-avoss** [comment] 2019-06-27 06:35
```
# rspamd -v
Rspamd daemon version 2.0 (current git-master)

# uname -msv
Linux #1 SMP PREEMPT Wed Jun 26 10:24:12 CEST 2019 x86_64

# /usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f -u rspamd -g rspamd
Segmentation fault
```

the above command to execute /usr/bin/rspamd produces the following log-message: 

`kernel: traps: rspamd[23098] general protection ip:7fdb4480e9d5 sp:7ffe9f27dd88 error:0 in librspamd-server.so[7fdb44645000+1cb000]`

rspamd was compiled with 'gcc (Gentoo Hardened 8.3.0-r1 p1.1) 8.3.0':

```
GIT update -->
   repository:               https://github.com/vstakhov/rspamd.git
   at the commit:            b7dbb7d1c7ca8716996b324e6e16de87c6646d7c

```

**Comment by vstakhov** [comment] 2019-06-27 08:42
I am investigating, sorry for the mess.

**Comment by int-avoss** [comment] 2019-06-27 10:44
the segfault is fixed on my hosts.

**Closed** 2019-06-27 22:32 UTC
Labels: bug
