### ISSUE TITLE
[BUG] *lua_redis_push_data: call to callback failed: Parse Error in file "<string>" on line 1, column 11: unknown or unexpected tag;

### ISSUE THREAD

**Issue by CAPSLOCK2000** [rspamd/rspamd#3054] opened 2019-09-25 09:05 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**lua_redis_push_data: call to callback failed: Parse Error in file "<string>" on line 1, column 11: unknown or unexpected tag;  **

I got the following error

2019-09-21 15:13:26 #30283(controller) lua_redis_push_data: call to callback failed: Parse Error in file "<string>" on line 1, column 11: unknown or unexpected tag; trace: [1]:{[C]:-1 - error [C]}; [2]:{/usr/share/rspamd/lualib/lupa.lua:69 - <unknown> [Lua]}; [3]:{[C]:-1 - match [C]}; [4]:{/usr/share/rspamd/lualib/lupa.lua:732 - jinja_template [Lua]}; [5]:{/usr/share/rspamd/plugins/dmarc.lua:930 - send_report_via_email [Lua]}; [6]:{/usr/share/rspamd/plugins/dmarc.lua:999 - callback [Lua]}; [7]:{/usr/share/rspamd/lualib/lua_redis.lua:985 - <unknown> [Lua]};

Reformatted for readability:
  2019-09-21 15:13:26 #30283(controller) lua_redis_push_data: call to callback failed:
  Parse Error in file "<string>" on line 1, column 11: unknown or unexpected tag;
  trace:
  [1]:{[C]:-1 - error [C]};
  [2]:{/usr/share/rspamd/lualib/lupa.lua:69 - <unknown> [Lua]};
  [3]:{[C]:-1 - match [C]};
  [4]:{/usr/share/rspamd/lualib/lupa.lua:732 - jinja_template [Lua]};
  [5]:{/usr/share/rspamd/plugins/dmarc.lua:930 - send_report_via_email [Lua]};
  [6]:{/usr/share/rspamd/plugins/dmarc.lua:999 - callback [Lua]};
  [7]:{/usr/share/rspamd/lualib/lua_redis.lua:985 - <unknown> [Lua]};

It seems to be a misspelled variable  in a Ninja template that uses 'report_domain' instead of 'reporting_domain'.

**Comment by CAPSLOCK2000** [comment] 2019-09-25 09:50
The pull request above does /not/ fix the bug, I just got hit again.

**Comment by wrosenauer** [comment] 2019-10-20 13:15
I have release 2.0 running and the same issue. Seems DMARC reports are not sent out right now since I updated from 1.9.4. Probably caused by this one.

**Comment by philr** [comment] 2019-10-22 23:22
I've opened pull request #3111 with a fix for this issue (and a couple of other problems that were causing DMARC reports to fail to be sent).

**Closed** 2019-10-23 11:35 UTC
Labels: bug
