### ISSUE TITLE
Rspamd fails to block forged local recipients

### ISSUE THREAD

**Issue by lavdnone** [rspamd/rspamd#2811] opened 2019-03-20 22:17 UTC
This fresh wave of spam with forging local emails is passing and passing through Rspamd.
Is there a tweak to block when local recipient is in FORGED_SENDER or FROM_NEQ_ENVFROM like in example below. It is clearly an issue.
We looked in if anyone else noticed something like this https://github.com/mailcow/mailcow-dockerized/issues/2458

3/20/2019, 9:15:10 AM	**pkozely@fl.com**	**pkozely@fl.com**	soft reject	[ 11.35 / 15 ]	unknown
IP address	74.220.217.46
Subject	pkozely
Symbols	HAS_X_SOURCE (0)
FROM_NEQ_ENVFROM (0) [**pkozely@fl.com,assistant@alkhair-coffee.com**]
FORGED_SENDER (0.3) [**pkozely@fl.com,assistant@alkhair-coffee.com**]
MIME_BASE64_TEXT (0.1)
TO_EQ_FROM (0)
RECEIVED_SPAMHAUS_PBL (0) [106.153.79.114.zen.spamhaus.org : 127.0.0.10]
MIME_TRACE (0) [0:+,1:+,2:+]
RCVD_TLS_LAST (0)
FROM_NO_DN (0)
FORGED_MUA_MOZILLA_MAIL_MSGID_UNKNOWN (2.5)
TO_DN_NONE (0)
TO_MATCH_ENVRCPT_ALL (0)
HAS_ORG_HEADER (0)
RCVD_COUNT_THREE (0) [4]
MX_INVALID (0.5) [cached]
DKIM_TRACE (0) [alkhair-coffee.com:-]
RCVD_VIA_SMTP_AUTH (0)
RCVD_IN_DNSWL_NONE (0) [46.217.220.74.list.dnswl.org : 127.0.5.0]
RECEIVED_SPAMHAUS_CSS (1) [106.153.79.114.zen.spamhaus.org : 127.0.0.3]
GREYLIST (0) [greylisted,Wed, 20 Mar 2019 13:19:30 GMT,body]
PREVIOUSLY_DELIVERED (0) [pkozely@fl.com]
ARC_NA (0)
DMARC_NA (0) [fl.com]
RECEIVED_BLOCKLISTDE (3) [106.153.79.114.bl.blocklist.de]
HAS_X_ANTIABUSE (0)
R_DKIM_REJECT (1) [alkhair-coffee.com:s=default]
R_SPF_SOFTFAIL (0) [~all]
ASN (0) [asn:46606, ipnet:74.220.192.0/19, country:US]
RCPT_COUNT_ONE (0) [1]
RCPT_MAILCOW_DOMAIN (0) [fl.com]
RECEIVED_SPAMHAUS_XBL (3) [106.153.79.114.zen.spamhaus.org : 127.0.0.4]
MIME_GOOD (-0.1) [multipart/related,multipart/alternative,text/plain]
IP_SCORE (0.05382) [country: US(0.27)]

**Comment by vstakhov** [comment] 2019-03-21 13:10
I don't understand your issue. Rspamd has no `magic` to understand what are local domains and what are not. It is your duty to tell it to Rspamd via, e.g. `multimap` plugin. Things you describe are definitely not caused by Rspamd malfunction, closing this issue.

**Closed by vstakhov** 2019-03-21 13:10 UTC

**Comment by lavdnone** [comment] 2019-03-22 15:00
Thanks, makes sense. Will try.
