### ISSUE TITLE
Compilation fails when building for ARM64 ?

### ISSUE THREAD

**Issue by alexAubin** [rspamd/rspamd#2202] opened 2018-04-28 21:41 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always (well I tried 2 times)
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

While trying to build rspamd for ARM64 for the YunoHost project, I encounted the following error during compilation (see below). Hopefully that makes sense to you somehow :P. Other builds for armel and amrhf worked fine.

### Compile errors (if any):

```
/usr/bin/cc    -g -O2 -fstrict-aliasing -g -O2 -fdebug-prefix-map=/build/rspamd-1.7.3+yunohost=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -pthread -fPIC  -W -Wall -Wpointer-arith -Wno-unused-parameter -Wno-unused-function -Wunused-variable -Wno-pointer-sign -Wstrict-prototypes -Wnull-dereference -Wduplicated-cond -Wno-unused-const-variable -Wno-sign-compare -std=c11 -DHAVE_RDTSC   -o CMakeFiles/cmTC_821e7.dir/src.c.o   -c /build/rspamd-1.7.3+yunohost/obj-aarch64-linux-gnu/CMakeFiles/CMakeTmp/src.c
/build/rspamd-1.7.3+yunohost/obj-aarch64-linux-gnu/CMakeFiles/CMakeTmp/src.c:2:23: fatal error: x86intrin.h: No such file or directory
 #include <x86intrin.h>
                       ^
compilation terminated.
CMakeFiles/cmTC_821e7.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_821e7.dir/src.c.o' failed
make[3]: *** [CMakeFiles/cmTC_821e7.dir/src.c.o] Error 1
make[3]: Leaving directory '/build/rspamd-1.7.3+yunohost/obj-aarch64-linux-gnu/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_821e7/fast' failed
make[2]: *** [cmTC_821e7/fast] Error 2
make[2]: Leaving directory '/build/rspamd-1.7.3+yunohost/obj-aarch64-linux-gnu/CMakeFiles/CMakeTmp'

Return value: 1
Source file was:

#include <x86intrin.h>
int main(int argc, char **argv) {
        __builtin_ia32_lfence ();
        if (__builtin_ia32_rdtsc()) {
                return 0;
        }
        return -1;
}
```

### Steps to reproduce:

Uh our toolchain is kinda complicated ... but I guess you could setup an ARM64 chroot with debootstrap and launch the build inside it :s ... (e.g. [this is what was used to create the ARM64 env](https://github.com/YunoHost/vinaigrette/blob/master/images/make-images#L15))

### Expected results:

Succesfull compilation like for armel and armhf :sweat_smile: 

### Actual results:

compilation error (c.f. above)

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

N/A I think ?

### Configuration:

N/A, none ?

### Additional information:

None for now ?

Cheers !

**Comment by alexAubin** [comment] 2018-05-25 02:48
I read the discussion on #2226 and #1351 and saw a possible fix was pushed so I have another try by compiling 1.7.5. Unfortunately I still get similar issue.

I noticed that many imports are not found : 

```
[...]/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:24: fatal error: sys/endian.h: No such file or directory
[...]/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:28: fatal error: machine/endian.h: No such file or directory
[...]/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:21: fatal error: siginfo.h: No such file or directory
[...]/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:28: fatal error: readpassphrase.h: No such file or directory
[...]/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:20: fatal error: libaio.h: No such file or directory
[...]/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:19: fatal error: cpuid.h: No such file or directory
[...]/CMakeFiles/CMakeTmp/CheckSymbolExists.c:2:19: fatal error: cpuid.h: No such file or directory
[...]/CMakeFiles/CMakeTmp/src.c:2:23: fatal error: x86intrin.h: No such file or directory
```

The compiler is GCC 6.3.0 which seems to work fine for other archs

**Comment by randomstuff** [comment] 2018-06-30 07:36
@alexAubin These "fatal errors" are normal. They happen in the feature detection part of cmake. What's your real error?

I tested building on a ARM64 chroot with Debian stretch on the master branch and I can't reproduce the OP error. Maybe this is fixed on the master branch? There should not be a x86intrin error as it's correctly feature detected AFAIU.

**Comment by randomstuff** [comment] 2018-06-30 07:46
I had to disable TORCH because luajit is not available on ARM64 however. This might be your problem.

**Comment by alexAubin** [comment] 2018-06-30 14:41
Indeed, as suggested by @randomstuff , setting luajit and torch to off here : https://github.com/vstakhov/rspamd/blob/master/debian/rules#L31-L32 I am able to compile on ARM64 (though I haveno idea what I'm doing and didnt actually test the deb yet :P )

**Closed** 2019-03-11 17:00 UTC
