### ISSUE TITLE
Fuzzy hashes should also check embedded images

### ISSUE THREAD

**Issue by AdUser** [rspamd/rspamd#698] opened 2016-07-04 01:40 UTC
Subj.
Example: spam-message consists from one really large image:

``` html
<DIV align=3Dcenter><A=20
href=3D"http://vk.cc/5lvnBI?/mykgm/cqpw.pdf"><IMG=20
border=3D0 hspace=3D0 alt=3D""=20
src=3D"cid:3FE21D611715447196FFA02C6A8024B3@mail.ru"></A></DIV>
```

```
--b64b7d006fa5c23c50fb007f7d0a
Content-Type: image/jpeg; name="fpd.jpg"
Content-Transfer-Encoding: base64
Content-ID: <3FE21D611715447196FFA02C6A8024B3@mail.ru>
/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP/sABFEdWNreQABAAQAAAA0AAD/4QNtaHR0cDov
```

Plaintext part almost empty, html part also contains only markup and fragment with link above.

**Comment by moisseev** [comment] 2016-07-04 06:46
For local fuzzy storage you can add `image/*` MIME type to fuzzy_check.conf:
~~~
rule "local" {
    ...
    mime_types = ["application/*", "image/*"];
    ...
}
~~~
@vstakhov I think you should add it to the "rspamd.com" storage as well.

**Comment by vstakhov** [comment] 2016-07-04 08:48
Rspamd implicitly uses all images and generate hashes for them.

**Comment by moisseev** [comment] 2016-07-04 08:51
That is not true. I checked with an embedded image.

**Comment by vstakhov** [comment] 2016-07-04 09:34
https://github.com/vstakhov/rspamd/blob/master/src/plugins/fuzzy_check.c#L2045

There is no condition to check images with the exception of height and width.

**Comment by moisseev** [comment] 2016-07-04 10:58
I've tested again with several embedded messages. It doesn't work. Rspamd doesn't check images unless `image/*` or `*` mime type configured explicitly.

**Comment by vstakhov** [comment] 2016-07-04 11:16
I've just tried it and I can clearly see that an image has been sent to fuzzy storage without mime type specification.

**Comment by moisseev** [comment] 2016-07-04 11:41
http://pastebin.com/kcYt7JK6
~~~
# rspamc fuzzy_add -f 11 -w 20 message.eml
Results for file: message.eml (0.004 seconds)
HTTP error: 404, No content to generate fuzzy for flag 11
~~~
~~~
# rspamadm configdump fuzzy_check
*** Section fuzzy_check ***
min_bytes = 100;
rule {
    rspamd.com {
        servers = "rspamd.com:11335";
        encryption_key = "icy63itbhhni8bq15ntp5n5symuixf73s1kpjh6skaq4e7nx5fiy";
        symbol = "FUZZY_UNKNOWN";
        mime_types [
            "application/*",
        ]
        max_score = 20.0;
        read_only = true;
        skip_unknown = true;
        fuzzy_map {
            FUZZY_DENIED {
                max_score = 20.0;
                flag = 1;
            }
            FUZZY_PROB {
                max_score = 10.0;
                flag = 2;
            }
            FUZZY_WHITE {
                max_score = 2.0;
                flag = 3;
            }
        }
    }
    local {
        servers = "localhost:11335";
        symbol = "LOCAL_FUZZY_UNKNOWN";
        max_score = 20.0;
        read_only = false;
        skip_unknown = true;
        fuzzy_map {
            LOCAL_FUZZY_DENIED {
                max_score = 20.0;
                flag = 11;
            }
            LOCAL_FUZZY_PROB {
                max_score = 10.0;
                flag = 12;
            }
            LOCAL_FUZZY_WHITE {
                max_score = 2.0;
                flag = 13;
            }
        }
    }
}
*** End of section fuzzy_check ***
~~~

**Comment by vstakhov** [comment] 2016-07-04 11:41
That's a different story, I think. Let me check...

**Comment by vstakhov** [comment] 2016-07-04 12:55
Nope, I can't reproduce this as well.

**Comment by vstakhov** [comment] 2016-07-04 13:00
Oh, wait I was able to reproduce it with exactly your message but not with some common that I have.

**Comment by vstakhov** [comment] 2016-07-04 13:22
Ok, that's unrelated issue: rspamd was unable to read Exif images. It is fixed now.

**Comment by moisseev** [comment] 2016-07-04 14:01
Ok, now rspamd learns and checks the sample message without mime specification.
I've added `min_height` and `min_width` to the configuration. I've tried different values, but the parameters do not affect neither learning nor checking. Rspamd processes image in any case.
~~~
*** Section fuzzy_check ***
min_bytes = 100;
...
    local {
        servers = "localhost:11335";
        symbol = "LOCAL_FUZZY_UNKNOWN";
        min_height = 1000;
        min_width = 1000;
        mime_types [
            "application/*",
        ]
        max_score = 20.0;
...
    }
}
*** End of section fuzzy_check ***
~~~

**Comment by vstakhov** [comment] 2016-07-16 22:46
It seems that rspamd cannot parse dimensions of EXIF jpeg files. I'll check.

**Comment by fatalbanana** [comment] 2018-02-24 21:05
Is this still relevant?

**Comment by moisseev** [comment] 2018-02-25 15:09
Unfortunately, the sample is lost.
btw, Why do we need to parse EXIF data even if it exists? Why not use "real" dimensions SOF0 (0xFFC0) anyway?

**Closed** 2019-04-02 01:27 UTC
Labels: wontfix
