### ISSUE TITLE
HFILTER_HELO_5(3.00) filter matches domain portion of address

### ISSUE THREAD

**Issue by Jayd603** [rspamd/rspamd#2140] opened 2018-04-03 01:57 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
all

This isn't that big of a deal but my business domain names are dyni.net, dynamicinternet.com, dynw.com and I'm getting hit by the DYN* regex entry.  I found this out installing rspamd on some machines here. How many hits does that get that are dynamically assigned IPs?  I don't think many people setting up access pool IPs are going to have anything but a "." after dyn.  However now that I think about it, an easy fix would be to only look for those in the host portion of the address and not within the domain name itself...  that wouldn't change the outcome of the rule at all for anyone.

I feel like i'm nagging raising this issue but hey if you were in my shoes you might consider doing the same thing.  :-)

Thanks

**Comment by moisseev** [comment] 2018-04-03 07:33
Actually hfilter uses more complex regexps than just `/dyn/`
Would you post full hostnames that matches`HFILTER_HELO_5` ?

**Comment by MinerGuy1111** [comment] 2018-04-03 07:42
I was being vague on purpose, I know they are not that simple but I did get a look at some of them , the code was in one of my searches.  corp1.dyni.net matches.

**Comment by moisseev** [comment] 2018-04-03 08:04
It matches this regexp
https://github.com/vstakhov/rspamd/blob/8308c7983fbdefd6ba72807888b1f7403d92a8f0/src/plugins/lua/hfilter.lua#L122
I think the regexp is too wide. As well as many others that don't ancored to dots or anything. E.g. `/[0-9][.-]?nat/i`.

**Comment by MinerGuy1111** [comment] 2018-04-20 17:28
Bump.

**Comment by moisseev** [comment] 2018-04-22 17:09
@MinerGuy1111 I guess these regexps was blindly copied from somewhere. We need someone to replace them with more strict regexps like [fqrdns.pcre](https://github.com/stevejenkins/hardwarefreak.com-fqrdns.pcre) (it is just an example) . Obviously no one volunteered to do that yet.

**Comment by vstakhov** [comment] 2018-04-22 19:13
Count me in. In case of hyperscan support enabled, we can port those regexps efficiently.

**Comment by moisseev** [comment] 2018-04-22 19:41
@vstakhov The problem is that `fqrdns` list is not maintained since the original author disappeared several years ago. I referred to it as an example of strict regexps.

**Comment by Jayd603** [comment] 2018-12-13 22:43
This has still not been resolved FYI

**Comment by Jayd603** [comment] 2018-12-14 16:30
I guess I'll need to try to find time to go edit/test these and submit a patch.. it's not just /dyn/ its a host of others that will hit people with a +3 for no good reason.

**Comment by Jayd603** [comment] 2019-01-11 17:23
If nobody is going to fix this could you lower the default score to maybe a 1 instead if a 3 please?

**Comment by Jayd603** [comment] 2019-03-25 17:47
Well it's a bug. Closing an active verified bug for being stale makes no sense.

**Comment by vstakhov** [comment] 2019-03-25 18:15
This bug has been fixed long time ago. Closing it in manual mode.

**Closed by vstakhov** 2019-03-25 18:15 UTC

**Comment by Jayd603** [comment] 2019-03-25 18:28
Ok I missed your update from January, my bad. 


-- 
James Dogopoulos 
https://DynamicInternet.com 
(877) 261-6511
