### ISSUE TITLE
Manual learning (spam/ham) for fuzzy

### ISSUE THREAD

**Issue by mnik247** [rspamd/rspamd#489] opened 2016-01-19 21:48 UTC
I try use local fuzzy:
    rule {
        servers = "127.0.0.1:11335";
        symbol = "LOCAL_FUZZY_UNKNOWN";
        mime_types = ["application/_", "_/octet-stream", "*"];
        max_score = 20.0;
        read_only = no;
        skip_unknown = yes;
        fuzzy_map = {
            LOCAL_FUZZY_DENIED {
                max_score = 20.0;
                flag = 1;
            }
            LOCAL_FUZZY_PROB {
                max_score = 10.0;
                flag = 2;
            }
            LOCAL_FUZZY_WHITE {
                max_score = -2.0;
                flag = 3;
            }
        }
}
And try learn for spam/ham.
for SPAM: rspamc -f 1 -w 1 fuzzy_add 1.msg
for HAM: rspamc -f 3 -w 1 fuzzy_add 1.msg
But I see it's not correct, because fuzzy use first used learning flag.
Can you help me with correct way for manual learning (spam/ham) for fuzzy?

**Comment by moisseev** [comment] 2016-01-19 22:02
Do you mean `rspamc -f 3 -w 1 fuzzy_add 1.msg` actually learns `LOCAL_FUZZY_DENIED` ? Could you post any evidence?

**Comment by mnik247** [comment] 2016-01-19 22:27
1) start check:
#rspamc  1.msg
Results for file: 1.msg (0.049 seconds)
[Metric: default]
Spam: false
Score: 9.19 / 100.00
Action: add header
Symbol: BAYES_HAM (-2.99)[99.99%]
Symbol: DATE_IN_PAST (1.00)
Symbol: FORGED_SENDER (0.30)
Symbol: HFILTER_URL_ONLY (3.50)
Symbol: MIME_HTML_ONLY (1.00)
Symbol: R_DKIM_ALLOW (-1.10)[bank.com]
Symbol: URIBL_BLACK (7.50)[emlportal.com.multi.uribl.com]
Message-ID: E1aHroj-0004ws-MJ@smtp1495.emltwo.com

2) learn as SPAM:
#rspamc -f 1 -w 1 fuzzy_add 1.msg
Results for file: 1.msg (0.002 seconds)
success = true;

3) check:
#rspamc  1.msg
Results for file: 1.msg (0.049 seconds)
[Metric: default]
Spam: false
Score: 10.55 / 100.00
Action: add header
Symbol: BAYES_HAM (-2.99)[99.99%]
Symbol: DATE_IN_PAST (1.00)
Symbol: FORGED_SENDER (0.30)
Symbol: HFILTER_URL_ONLY (3.50)
Symbol: LOCAL_FUZZY_DENIED (1.35)[1: 1.00 / 0.13]
Symbol: MIME_HTML_ONLY (1.00)
Symbol: R_DKIM_ALLOW (-1.10)[bank.com]
Symbol: URIBL_BLACK (7.50)[emlportal.com.multi.uribl.com]
Message-ID: E1aHroj-0004ws-MJ@smtp1495.emltwo.com

4)learn as HAM:
#rspamc -f 3 -w 1 fuzzy_add 1.msg
Results for file: 1.msg (0.002 seconds)
success = true;

5)check:
#rspamc  1.msg
Results for file: 1.msg (0.050 seconds)
[Metric: default]
Spam: false
Score: 11.56 / 100.00
Action: add header
Symbol: BAYES_HAM (-2.99)[99.99%]
Symbol: DATE_IN_PAST (1.00)
Symbol: FORGED_SENDER (0.30)
Symbol: HFILTER_URL_ONLY (3.50)
Symbol: LOCAL_FUZZY_DENIED (2.65)[1: 1.00 / 0.26]
Symbol: LOCAL_FUZZY_WHITE (-0.28)[3: 1.00 / 0.13]
Symbol: MIME_HTML_ONLY (1.00)
Symbol: R_DKIM_ALLOW (-1.10)[bank.com]
Symbol: URIBL_BLACK (7.50)[emlportal.com.multi.uribl.com]
Message-ID: E1aHroj-0004ws-MJ@smtp1495.emltwo.com

And very strange - I got that wanted, but couldn't get before:
Symbol: LOCAL_FUZZY_DENIED (2.65)[1: 1.00 / 0.26]
Symbol: LOCAL_FUZZY_WHITE (-0.28)[3: 1.00 / 0.13]

**Comment by vstakhov** [comment] 2016-01-19 22:32
The problem is in the probabilistic part called 'shingles'. Shingles are associated with some specific hash and if the same hash is in the different lists then the overall behaviour is not very well defined. The proper way is to remove old hash (using `fuzzy_del`) that cleans all associated shingles and add it again to another list.

**Comment by moisseev** [comment] 2016-01-19 22:38
He expects the results immediately.

@mnik247, you got results from previous learning attempt. 1.1.x updates fuzzy storage once per minute. You have to wait before check.

@vstakhov BTW is there some way to force the update? It could be useful for manual learning to have immediate feedback.

**Comment by mnik247** [comment] 2016-01-19 22:42
It will not manual learning - it will learning from users marked "SPAM/HAM" by scripts.
And I know very often users mark normal message as "SPAM", and then mark 
it again  as "HAM".

**Comment by mnik247** [comment] 2016-01-20 00:13
I try continue test  and...
5)learn as HAM:
#rspamc -f 3 -w 1 fuzzy_add 1.msg
#rspamc -f 3 -w 1 fuzzy_add 1.msg

6) after 1 minute:
#rspamc  /1.msg
Results for file: /1.msg (0.049 seconds)
[Metric: default]
Spam: false
Score: 13.34 / 100.00
Action: add header
Symbol: LOCAL_FUZZY_DENIED (4.95)[1: 1.00 / 0.49]
Symbol: LOCAL_FUZZY_WHITE (-0.81)[3: 1.00 / 0.38]
Message-ID: E1aHroj-0004ws-MJ@smtp1495.emltwo.com

7)learn as HAM:
#rspamc -f 3 -w 1 fuzzy_add /1.msg
Results for file: /1.msg (0.002 seconds)
success = true;

8) after 1 minute:
#rspamc  /1.msg
Results for file: /1.msg (0.110 seconds)
[Metric: default]
Spam: false
Score: 14.07 / 100.00
Symbol: LOCAL_FUZZY_DENIED (5.91)[1: 1.00 / 0.59]
Symbol: LOCAL_FUZZY_WHITE (-1.04)[3: 1.00 / 0.49]
Message-ID: E1aHroj-0004ws-MJ@smtp1495.emltwo.com

9)learn as SPAM:
#rspamc -f 1 -w 1 fuzzy_add /1.msg

10) after 1 minute:
#rspamc  /1.msg
Results for file: /1.msg (0.049 seconds)
[Metric: default]
Spam: false
Score: 14.68 / 100.00
Symbol: LOCAL_FUZZY_DENIED (6.72)[1: 1.00 / 0.67]
Symbol: LOCAL_FUZZY_WHITE (-1.24)[3: 1.00 / 0.59]
Message-ID: E1aHroj-0004ws-MJ@smtp1495.emltwo.com

I see LOCAL_FUZZY_DENIED  and LOCAL_FUZZY_WHITE changed together and not depend from learning flag (spam/ham) ...

**Comment by xpunkt** [comment] 2016-01-20 00:32
to unlearn use fuzzy_del

**Comment by moisseev** [comment] 2016-01-20 07:41
@vstakhov I confirm the issue. If the hash is already in the fuzzy storage, rspamd updates it regardless of a flag.
Tested with 90423f1
~~~
# rspamc bugzilla.eml -t 20 | grep FUZZY

# rspamc -w 1 -f 11 fuzzy_add bugzilla.eml
Results for file: bugzilla.eml (0.002 seconds)
success = true;

# rspamc bugzilla.eml -t 20 | grep FUZZY
Symbol: LOCAL_FUZZY_DENIED (1.35)[11: 1.00 / 0.13, 11: 1.00 / 0.13]

# rspamc -w 1 -f 13 fuzzy_add bugzilla.eml
Results for file: bugzilla.eml (0.002 seconds)
success = true;

# rspamc bugzilla.eml -t 20 | grep FUZZY
Symbol: LOCAL_FUZZY_DENIED (2.65)[11: 1.00 / 0.26, 11: 1.00 / 0.26]

# rspamc -w 1 -f 13 fuzzy_add bugzilla.eml
Results for file: bugzilla.eml (0.002 seconds)
success = true;

# rspamc bugzilla.eml -t 20 | grep FUZZY
Symbol: LOCAL_FUZZY_DENIED (3.86)[11: 1.00 / 0.38, 11: 1.00 / 0.38]

# rspamc -f 13 fuzzy_del bugzilla.eml
Results for file: bugzilla.eml (0.002 seconds)
success = true;

# rspamc bugzilla.eml -t 20 | grep FUZZY
Symbol: LOCAL_FUZZY_DENIED (3.86)[11: 1.00 / 0.38, 11: 1.00 / 0.38]

# rspamc bugzilla.eml -t 20 | grep FUZZY

# rspamc -w 1 -f 13 fuzzy_add bugzilla.eml
Results for file: bugzilla.eml (0.002 seconds)
success = true;

# rspamc bugzilla.eml -t 20 | grep FUZZY
Symbol: LOCAL_FUZZY_WHITE (-0.28)[13: 1.00 / 0.13, 13: 1.00 / 0.13]


# rspamc -w 1 -f 11 fuzzy_add bugzilla.eml
Results for file: bugzilla.eml (0.001 seconds)
success = true;

# rspamc bugzilla.eml -t 20 | grep FUZZY
Symbol: LOCAL_FUZZY_WHITE (-0.55)[13: 1.00 / 0.26, 13: 1.00 / 0.26]
~~~
~~~
fuzzy_check {
    # Include dynamic conf for the rule
    .include(try=true,priority=1) "${DBDIR}/dynamic/fuzzy_check.conf"
    min_bytes = 100;
    rule {
        servers = "localhost:11335";
        symbol = "LOCAL_FUZZY_UNKNOWN";
        mime_types = "application/pdf";
        mime_types = "*";
        max_score = 20.0;
        read_only = no;
        skip_unknown = yes;
        fuzzy_map = {
            LOCAL_FUZZY_DENIED {
                max_score = 20.0;
                flag = 11;
            }
            LOCAL_FUZZY_PROB {
                max_score = 10.0;
                flag = 12;
            }
            LOCAL_FUZZY_WHITE {
                max_score = 2.0;
                flag = 13;
            }
        }
    }
}
~~~

**Comment by vstakhov** [comment] 2016-01-25 00:13
Well, I've changed addresses parsing in the recent master. Could you please check if it solves your issue?

**Comment by moisseev** [comment] 2016-01-25 07:00
Addresses parsing doesn't affect this issue. I've responded in #478

**Comment by mnik247** [comment] 2016-01-25 09:22
@vstakhov 
I don't see last nightly builds for Centos 6 and can't check.
What commit(s) for "changed addresses parsing in the recent master"? 
I will rebuild my rpm for Centos 6.

**Comment by moisseev** [comment] 2016-01-25 09:35
@mnik d100deb - f624af1, but I'm positive that @vstakhov's latest reply is not related to **this** issue.

**Comment by mnik247** [comment] 2016-01-25 15:17
@vstakhov 
1) rebuild rpm for Centos 6 from git df4b3f74fc99f40d9009c0d621cb39359b61b506
2) result testing - fuzzy learning ignore flag after first learning and use only flag from first learning.

**Comment by mnik247** [comment] 2016-01-26 14:12
@vstakhov 
Do you have any comments?

**Comment by vstakhov** [comment] 2016-01-26 14:14
My comment is listed here: use `fuzzy_del` to relearn.

**Comment by moisseev** [comment] 2016-01-26 16:03
It seems I've got it.
There was a bug in the fuzzy storage (#478) and shingles has never been used.
If we learn the same digest  as `FUZZY_WHITE` and `FUZZY_DENIED` we'll get two symbols on scaning `FUZZY_WHITE` and `FUZZY_DENIED` at the same time. Subsequent ham learns decreases ham score and spam learns increases spam score. Of course, we can use `fuzzy_del` if false positive detected. This behavior was simple and predictable.

But now the bug with shingles is fixed. And we've got unexpected (for some of us) learning behavior. If we learn ham message, but fuzzy storage already contains matching shingle(s) marked as spam, score of that "spam" shigle(s) will be increased.
Now to avoid learning ham as spam (or vice versa) we have to scan the message before every learning attempt. And use `fuzzy_del` if matching shingles was already stored with different flag.

@vstakhov Am I right? That looks pretty complicated. Is it possible at least to add some learning protection for such cases?

**Comment by vstakhov** [comment] 2016-01-26 17:50
@moisseev thank you for such a detailed investigation. The issue is now clear for me and I've committed a potential fix to it: now fuzzy storage should update flag and reset weight to the sane value.

**Comment by moisseev** [comment] 2016-01-26 19:45
@vstakhov Looks like `fuzzy_learn` works as expected.
How do you think should `fuzzy_del` __respect__ flags? For now it deletes matching shingles regardless of the flag.

What about my other question? While testing it's really annoying to wait whole minute to get the results after each iteration. Is there some way to force the update? It could be also quite useful for manual learning to have immediate feedback. Maybe you can add a rspamc command?

**Comment by digitalkram** [comment] 2018-02-25 17:20
hi there

I am going to hijack this well-aged issue thread with a slightly related question:
In this thread here there is often the statment that one can "use fuzzy_del to unlearn a message".

I currently have the problem that a lot of messages were learned as ham (incorrectly, is fixed now) but I want them to be trained as spam but I get (when trying to learn it as spam):
```
HTTP error: 410, <c2b269e2e1b453fe253e01553c13be2b@tiantianxo.com> is skipped for bayes classifier: already in class ham; probability 100.00%
```
So I thought I'd fuzzy_del it first before learning it as Spam but I am unable to 

a) find documentation what the -f flags are (Where?) - the last post sounds like they doesn't matter for fuzzy_del anyways  and
b) how unlearning command is written correctly.


I tried
```
rspamc -f 1 fuzzy_del <file>
```

with various numbers for -f but I get either
```
HTTP error: 404, Unknown or missing flag
```

or

```
HTTP error: 403, Message is conditionally skipped for flag <flag value>
```

So how do I unlearn correctly?

Thanks for any pointer!

**Comment by moisseev** [comment] 2018-02-25 18:51
@digitalkram , you mixed-up fuzzy and bayes.
You cannot delete bayes tokens, but you can retrain ham as spam and vice versa.
To train as spam:
```
# rspamc learn_spam filename.eml
```
Or you can specify a directory instead of filename.

To delete fuzzy hashes from **your local** fuzzy storage (if you have one) you can find flags in the fuzzy storage configuration. See local.d/fuzzy_check.conf.

**Comment by digitalkram** [comment] 2018-02-25 20:29
@moisseev Oh man! I feel so stupid now. Yes, a mix-up plus I managed to use learn_ham while thinking I was using learn_spam which mad me misinterpret the output... 😊

**Closed** 2019-04-02 01:27 UTC
Labels: wontfix
