### ISSUE TITLE
got error WRONGTYPE Operation in Redis since recent update

### ISSUE THREAD

**Issue by gregober** [rspamd/rspamd#4969] opened 2024-05-14 16:29 UTC
Until a recent upgrade I now have these issue with the history display in the rspamd: 

> got error WRONGTYPE Operation against a key holding the wrong kind of value when writing history row: no value

I think this is a redis key problem, but IDK where in redis to look in order to fix this issue. 

rspamd logs show pb in "rspamd_proxy and controller": 

```
14/05/2024 18:20:44	rspamd_proxy	597	lua	535fd7	got error WRONGTYPE Operation against a key holding the wrong kind of value when writing history row: no value
14/05/2024 18:15:43	rspamd_proxy	597	lua	78594e	got error WRONGTYPE Operation against a key holding the wrong kind of value when writing history row: no value
14/05/2024 18:13:53	controller	599	lua	2a81d8	got error WRONGTYPE Operation against a key holding the wrong kind of value when getting history: no value

```

Any help on how to fix this would be greatly appreciated. 
thx

**Comment by moisseev** [comment] 2024-05-14 16:40
Duplicate of #4828

**Closed** 2024-05-15 14:52 UTC
