### ISSUE TITLE
[BUG] rspamd web interface breaked

### ISSUE THREAD

**Issue by Neurozone** [rspamd/rspamd#2858] opened 2019-04-17 17:01 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
After reading many tutos and the official documentation, rspamd web interface still broke

### Steps to Reproduce

1. going to https://mymaildomain/rspamd/

**Expected behavior**
showing rspamd web interface

### Versions

Rspamd daemon version 1.9.2
CentOS 7.6
Nginx latest

### Additional Information

error log from nginx:
2019/04/17 18:56:25 [error] 27892#0: *44 open() "/path/to/mail/application/php/rspamd/img/rspamd_logo_navbar.png" failed (2: No such file or directory), client: 78.192.60.82, server: mail.mydomain.tld, request: "GET /rspamd/img/rspamd_logo_navbar.png HTTP/2.0", host: "mail.mydomain.tld", referrer: "https://mail.mydomain.tld/rspamd/"
2019/04/17 18:56:25 [error] 27892#0: *44 open() "/path/to/mail/application/php/rspamd/css/bootstrap.min.css" failed (2: No such file or directory), client: 78.192.60.82, server: mail.mydomain.tld, request: "GET /rspamd/css/bootstrap.min.css HTTP/2.0", host: "mail.mydomain.tld", referrer: "https://mail.mydomain.tld/rspamd/"
2019/04/17 18:56:25 [error] 27892#0: *44 open() "/path/to/mail/application/php/rspamd/css/footable.bootstrap.min.css" failed (2: No such file or directory), client: 78.192.60.82, server: mail.mydomain.tld, request: "GET /rspamd/css/footable.bootstrap.min.css HTTP/2.0", host: "mail.mydomain.tld", referrer: "https://mail.mydomain.tld/rspamd/"
2019/04/17 18:56:25 [error] 27892#0: *44 open() "/path/to/mail/application/php/rspamd/css/d3evolution.css" failed (2: No such file or directory), client: 78.192.60.82, server: mail.mydomain.tld, request: "GET /rspamd/css/d3evolution.css HTTP/2.0", host: "mail.mydomain.tld", referrer: "https://mail.mydomain.tld/rspamd/"
2019/04/17 18:56:25 [error] 27892#0: *44 open() "/path/to/mail/application/php/rspamd/css/nprogress.css" failed (2: No such file or directory), client: 78.192.60.82, server: mail.mydomain.tld, request: "GET /rspamd/css/nprogress.css HTTP/2.0", host: "mail.mydomain.tld", referrer: "https://mail.mydomain.tld/rspamd/"
2019/04/17 18:56:25 [error] 27892#0: *44 open() "/path/to/mail/application/php/rspamd/css/rspamd.css" failed (2: No such file or directory), client: 78.192.60.82, server: mail.mydomain.tld, request: "GET /rspamd/css/rspamd.css HTTP/2.0", host: "mail.mydomain.tld", referrer: "https://mail.mydomain.tld/rspamd/"
2019/04/17 18:56:25 [error] 27892#0: *44 open() "/path/to/mail/application/php/rspamd/js/lib/require.min.js" failed (2: No such file or directory), client: 78.192.60.82, server: mail.mydomain.tld, request: "GET /rspamd/js/lib/require.min.js HTTP/2.0", host: "mail.mydomain.tld", referrer: "https://mail.mydomain.tld/rspamd/"
2019/04/17 18:56:25 [error] 27892#0: *44 open() "/path/to/mail/application/php/favicon.ico" failed (2: No such file or directory), client: 78.192.60.82, server: mail.mydomain.tld, request: "GET /favicon.ico HTTP/2.0", host: "mail.mydomain.tld"
2019/04/17 18:56:25 [error] 27892#0: *44 open() "/path/to/mail/application/php/favicon.ico" failed (2: No such file or directory), client: 78.192.60.82, server: mail.mydomain.tld, request: "GET /favicon.ico HTTP/2.0", host: "mail.mydomain.tld"

nginx configuration:

server
{

  listen   80;
  server_name mail.mydomain.tld;
  root /data/www/mail.mydomain.tld;

  access_log /var/log/nginx/access.mail.mydomain.tld.log;
  error_log /var/log/nginx/error.mail.mydomain.tld.log;

  index index.php;

  location /rspamd/ {
    #proxy_pass http://127.0.0.1:11334/;
    proxy_pass http://unix:/run/rspamd/worker-controller.socket:/;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_http_version 1.1;
  }

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ /\.ht {
    deny all;
  }

  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_split_path_info ^(.+\.php)(.*)$;
    fastcgi_keep_conn on;
    include fastcgi_params;
  }

  location ^~ /data {
    deny all;
  }

  location ~*  \.(jpg|jpeg|png|gif|ico|css|js)$ {
    expires 365d;
  }

  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/mail.mydomain.tld/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/mail.mydomain.tld/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot

  if ($scheme != "https") {
    return 301 https://$host$request_uri;
   } # managed by Certbot

}

local.d/worker-controller.inc

password = "";
enable_password = "";
bind_socket = "127.0.0.1:11334";
bind_socket = "/run/rspamd/worker-controller.socket mode=0666 owner=nobody group=nginx";

**Comment by Neurozone** [comment] 2019-04-17 17:05
![rspamd](https://user-images.githubusercontent.com/5229035/56306781-a591a700-6143-11e9-9438-eebf9cea2ad7.jpg)

I don't understand why :(

**Comment by vstakhov** [comment] 2019-04-29 11:43
Not a bug, closing as inappropriate for issue tracker.

**Closed by vstakhov** 2019-04-29 11:43 UTC
Labels: bug

**Comment by alextovey** [comment] 2019-10-02 12:42
actually this is a bug! i've got the same issue.

**Comment by citizenz7** [comment] 2019-10-04 19:07
Same issue here on a fresh install.

**Comment by pimytron** [comment] 2019-12-05 20:54
Same issue here. Has anyone solved it?

**Comment by alexbasnett** [comment] 2019-12-24 21:09
**For anybody else finding this in the future the answer is:**

Access the gui as: https://sub.domain.com/rspamd/
NOT https://sub.domain.com/rspamd

**The final slash is key.**


@pimytron 
@citizenz7 
@alextovey
