### ISSUE TITLE
[QUESTION] MX Whitelist

### ISSUE THREAD

**Issue by celevra** [rspamd/rspamd#2869] opened 2019-04-24 09:44 UTC
Hi,

i've tried to understand the documentation but don't get it.
I'm get mails from an external domain that is trying to send mails for a spf protected Domain and gets rejected.
i want to whitelist not a single mail server from that domain but the whole domain like
if the mail is from a stmp from *.microsoft.com then don't do any checks
is this possible?

regards

Celevra

**Comment by vstakhov** [comment] 2019-04-29 11:41
Not a bug, closing as inappropriate for issue tracker.

**Closed by vstakhov** 2019-04-29 11:41 UTC
