### ISSUE TITLE
Rspamd overloades Redis

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#2873] opened 2019-04-26 10:20 UTC
### Bug Description
Rspamd overloades Redis although modules using Redis are disabled.

### Steps to Reproduce
Disable all modules:

`rspamadm configwizard:`
> Welcome to the configuration tool
We use /etc/rspamd/rspamd.conf configuration file, writing results to /etc/rspamd
Modules enabled: settings
Modules disabled (explicitly): spamassassin, dkim_signing, mx_check, arc, maillist, metadata_exporter, multimap, surbl, dmarc, milter_headers, whitelist, neural, trie, hfilter, phishing, reputation, mime_types, asn, rspamd_update, ip_score, url_tags, url_redirector, mid, url_reputation, rbl, emails, antivirus, dcc, history_redis, greylist, once_received, forged_recipients, spamtrap, ratelimit, force_actions, replies
Modules disabled (unconfigured): maps_stats, metric_exporter, dynamic_conf, clustering, bayes_expiry, fuzzy_collect, external_services, clickhouse, elastic
Modules disabled (no Redis): 
Modules disabled (experimental): 
Modules disabled (failed): 

Aggregated output of executed command for several seconds
`redis-cli monitor | sed -E 's/.*sock[]][ ](.*)/\1/' | sort | uniq -c`

>    2463 "EXEC"
      6 "HGET" "BAYES_HAM" "learns_ham"
     12 "HGET" "BAYES_SPAM" "learns_spam"
      2 "HGET" "RS_10002172590256131957" "H"
      2 "HGET" "RS_10002172590256131957" "S"
      1 "HGET" "RS_10009936498148019312" "H"
      1 "HGET" "RS_10009936498148019312" "S"
   1117 "HGET" "RS_10010131977645279776" "H"
   1118 "HGET" "RS_10010131977645279776" "S"
   .
   .
   .
   1 "HGET" "RS_9999124060368247154" "H"
   1 "HGET" "RS_9999124060368247154" "S"
   2310 "HGET" "RS" "learns_ham"
   2316 "HGET" "RS" "learns_spam"
   4607 "MULTI"
      1 OK
      6 "SMEMBERS" "BAYES_HAM_keys"
     12 "SMEMBERS" "BAYES_SPAM_keys"

which causes 100% load of Redis during standard traffic.
No other process is using monitored instance of redis.

**Expected behavior**
Negligible load on Redis when all modules in Rspamd disabled.

### Versions
1.9.0

**Comment by vstakhov** [comment] 2019-04-26 10:45
Bayes is special. It is not treated as module at all. You need to disable redis statisctical backend. Not a bug, closing.

**Closed by vstakhov** 2019-04-26 10:45 UTC
Labels: bug
