### ISSUE TITLE
spf_dkim whitelist does not work

### ISSUE THREAD

**Issue by andy-igoshin** [rspamd/rspamd#2646] opened 2018-11-25 13:49 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.8.1, 1.8.2

### Operation system, CPU:

linux, x64

### Description (Please provide a descriptive summary of the issue):

Symbol: R_DKIM_ALLOW (-0.20)[emails.wahoofitness.com:s=scph0918]
Symbol: R_SPF_ALLOW (-0.20)[+exists:54.218.127.40._spf.e.sparkpost.com]

but whitelist does not trigger.

### Expected results:

whitelist triggers

### Actual results:

whitelist does not trigger.

### Additional information:

$ rspamc 22055-P.txt 
Results for file: 22055-P.txt (1.016 seconds)
[Metric: default]
Action: add header
Spam: true
Score: 7.36 / 15.00
Symbol: ARC_NA (0.00)
Symbol: ASN (0.00)[asn:16509, ipnet:54.218.0.0/17, country:US]
Symbol: BAYES_SPAM (2.47)[91.34%]
Symbol: DATE_IN_PAST (1.00)
Symbol: DKIM_TRACE (0.00)[emails.wahoofitness.com:+]
Symbol: DMARC_NA (0.00)[wahoofitness.com]
Symbol: FROM_HAS_DN (0.00)
Symbol: FROM_NEQ_ENVFROM (0.00)[noreply@emails.wahoofitness.com, bounces@sp.crdl.io]
Symbol: HAS_LIST_UNSUB (-0.01)
Symbol: HAS_REPLYTO (0.00)[noreply@emails.wahoofitness.com]
Symbol: HTML_SHORT_LINK_IMG_1 (2.00)
Symbol: MANY_INVISIBLE_PARTS (1.00)[10]
Symbol: MIME_HTML_ONLY (0.20)
Symbol: ONCE_RECEIVED (0.10)
Symbol: RCPT_COUNT_ONE (0.00)[1]
Symbol: RCVD_COUNT_ONE (0.00)[1]
Symbol: RCVD_IN_DNSWL_NONE (0.00)[40.127.218.54.list.dnswl.org : 127.0.10.0]
Symbol: RCVD_TLS_ALL (0.00)
Symbol: REPLYTO_ADDR_EQ_FROM (0.00)
Symbol: R_DKIM_ALLOW (-0.20)[emails.wahoofitness.com:s=scph0918]
Symbol: R_SPF_ALLOW (-0.20)[+exists:54.218.127.40._spf.e.sparkpost.com]
Symbol: SUBJECT_ENDS_EXCLAIM (0.00)
Symbol: TAGGED_FROM (0.00)[svg=org.vrn.ru]
Symbol: TO_DN_NONE (0.00)
Symbol: ZERO_FONT (1.00)[13]
Message-ID: 1A.DB.05729.0E727FB5@w.mta2vrest.cc.prd.sparkpost
Message - spf: (SPF): spf allow

**Comment by andy-igoshin** [comment] 2018-11-25 13:52
[22055-P.txt](https://github.com/rspamd/rspamd/files/2613126/22055-P.txt)

sample mail attached.

**Comment by vstakhov** [comment] 2018-11-25 17:35
I'm not sure that dkim whitelist would work for subdomains.

**Comment by andy-igoshin** [comment] 2018-11-25 19:37
it worked unti version 1.8.1.

**Comment by tjharman** [comment] 2018-12-06 22:15
I'm not 100% sure this is resolved in 1.8.3.
For example, github is in the included default 

```
root@micro:/etc/rspamd# grep github spf_dkim_whitelist.inc
github.com 2.0
```
But in the emails I get from GitHub, I don't see the whitelist firing:

```
BAYES_HAM (-3) [100.00%]
IP_SCORE (-1.801666) [ipnet: 192.30.252.0/24(-4.96), asn: 36459(-3.97), country: US(-0.09)]
RWL_HOSTKARMA_WHITE (-1.5) [194.252.30.192.hostkarma.junkemailfilter.com : 127.0.0.1]
RCVD_DKIM_ARC_DNSWL_HI (-1)
URI_COUNT_ODD (1) [3]
DMARC_POLICY_ALLOW (-0.5) [github.com,none]
RCVD_IN_DNSWL_HI (-0.5) [194.252.30.192.list.dnswl.org : 127.0.9.3]
MV_CASE (0.5)
RWL_HOSTKARMA_QUIT_USED (-0.25) [194.252.30.192.hostkarma.junkemailfilter.com : 127.0.1.1]
R_SPF_ALLOW (-0.2) [+ip4:192.30.252.0/22]
R_DKIM_ALLOW (-0.2) [github.com:s=pf2014]
MIME_GOOD (-0.1) [multipart/alternative,text/plain]
MAILLIST (-0.1) [generic]
MX_GOOD (-0.01) [cached: ALT3.ASPMX.L.GOOGLE.com]
HAS_LIST_UNSUB (-0.01)
FROM_NEQ_ENVFROM (0) [notifications@github.com,noreply@github.com]
ASN (0) [asn:36459, ipnet:192.30.252.0/24, country:US]
DKIM_TRACE (0) [github.com:+]
TO_DN_ALL (0)
MIME_TRACE (0) [0:+,1:+]
RCVD_TLS_ALL (0)
HAS_REPLYTO (0) [reply+000fa405aa4ebeab8c03146c2b18dd58ff80e86f25df2ff492cf0000000118209e1092a169ce171a832c@reply.github.com]
MID_RHS_MATCH_FROM (0)
REPLYTO_DOM_NEQ_FROM_DOM (0)
RBL_COMPOSITE_RCVD_IN_DNSWL_HI_DWL_DNSWL_HI (0)
RCPT_COUNT_THREE (0) [3]
ARC_NA (0)
TO_MATCH_ENVRCPT_SOME (0)
RCVD_COUNT_ZERO (0) [0]
FROM_HAS_DN (0)
FORGED_SENDER_MAILLIST (0)
```

```
BAYES_HAM (-3) [100.00%]
IP_SCORE (-1.801717) [ipnet: 192.30.252.0/24(-4.96), asn: 36459(-3.97), country: US(-0.09)]
RWL_HOSTKARMA_WHITE (-1.5) [193.252.30.192.hostkarma.junkemailfilter.com : 127.0.0.1]
RCVD_DKIM_ARC_DNSWL_HI (-1)
URI_COUNT_ODD (1) [5]
DMARC_POLICY_ALLOW (-0.5) [github.com,none]
RCVD_IN_DNSWL_HI (-0.5) [193.252.30.192.list.dnswl.org : 127.0.9.3]
MV_CASE (0.5)
URL_IN_SUBJECT (0.4) [whitelist.md]
RWL_HOSTKARMA_QUIT_USED (-0.25) [193.252.30.192.hostkarma.junkemailfilter.com : 127.0.1.1]
R_SPF_ALLOW (-0.2) [+ip4:192.30.252.0/22]
R_DKIM_ALLOW (-0.2) [github.com:s=pf2014]
MAILLIST (-0.1) [generic]
MIME_GOOD (-0.1) [multipart/alternative,text/plain]
MX_GOOD (-0.01) [cached: ALT3.ASPMX.L.GOOGLE.com]
HAS_LIST_UNSUB (-0.01)
ASN (0) [asn:36459, ipnet:192.30.252.0/24, country:US]
FROM_NEQ_ENVFROM (0) [notifications@github.com,noreply@github.com]
MIME_TRACE (0) [0:+,1:+]
DKIM_TRACE (0) [github.com:+]
TO_DN_ALL (0)
REPLYTO_DOM_NEQ_FROM_DOM (0)
RCVD_TLS_ALL (0)
HAS_REPLYTO (0) [reply+000fa40553026b11ad1a3ac2f08741273bf281793d1fdb8892cf000000011821551592a169ce17268e8c@reply.github.com]
FORGED_SENDER_MAILLIST (0)
RBL_COMPOSITE_RCVD_IN_DNSWL_HI_DWL_DNSWL_HI (0)
RCVD_COUNT_ZERO (0) [0]
ARC_NA (0)
TO_MATCH_ENVRCPT_SOME (0)
RCPT_COUNT_THREE (0) [3]
FROM_HAS_DN (0)
MID_RHS_MATCH_FROM (0)
```

```
root@micro:/etc/rspamd# rspamadm configdump whitelist
*** Section whitelist ***
rules {
    WHITELIST_DMARC {
        inverse_symbol = "BLACKLIST_DMARC";
        score = -7;
        domains [
            "https://maps.rspamd.com/rspamd/dmarc_whitelist_new.inc.zst",
            "/var/lib/rspamd/dmarc_whitelist.inc.local",
            "fallback+file:///etc/rspamd/dmarc_whitelist.inc",
        ]
        valid_dmarc = true;
    }
    WHITELIST_SPF_DKIM {
        valid_spf = true;
        inverse_symbol = "BLACKLIST_SPF_DKIM";
        domains [
            "https://maps.rspamd.com/rspamd/spf_dkim_whitelist.inc.zst",
            "/var/lib/rspamd/spf_dkim_whitelist.inc.local",
            "fallback+file:///etc/rspamd/spf_dkim_whitelist.inc",
        ]
        valid_dkim = true;
        score = -3;
    }
    WHITELIST_DKIM {
        inverse_symbol = "BLACKLIST_DKIM";
        domains [
            "/var/lib/rspamd/dkim_whitelist.inc.local",
            "fallback+file:///etc/rspamd/dkim_whitelist.inc",
        ]
        valid_dkim = true;
        score = -1;
    }
    WHITELIST_SPF {
        inverse_symbol = "BLACKLIST_SPF";
        domains [
            "/var/lib/rspamd/spf_whitelist.inc.local",
            "fallback+file:///etc/rspamd/spf_whitelist.inc",
        ]
        valid_spf = true;
        score = -1;
    }
}

*** End of section whitelist ***
```

**Comment by vstakhov** [comment] 2018-12-08 12:50
I cannot reproduce it I'm afraid.

**Comment by vstakhov** [comment] 2019-03-11 11:00
No feedback, closing.

**Closed by vstakhov** 2019-03-11 11:00 UTC
Labels: bug
