### ISSUE TITLE
No corresponding rule registered

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#2835] opened 2019-04-03 14:40 UTC
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.9
### Description (Please provide a descriptive summary of the issue):
Output of _rspamadm configtest_ command:

> symbol 'BLACKLIST_DKIM' has its score defined but there is no corresponding rule registered
symbol 'BLACKLIST_DMARC' has its score defined but there is no corresponding rule registered
symbol 'BLACKLIST_SPF' has its score defined but there is no corresponding rule registered
symbol 'BLACKLIST_SPF_DKIM' has its score defined but there is no corresponding rule registered
symbol 'ARC_NA' has its score defined but there is no corresponding rule registered
symbol 'ARC_DNSFAIL' has its score defined but there is no corresponding rule registered
symbol 'ARC_ALLOW' has its score defined but there is no corresponding rule registered
symbol 'ARC_REJECT' has its score defined but there is no corresponding rule registered
symbol 'ARC_INVALID' has its score defined but there is no corresponding rule registered

### Expected results:
No log message "... has its score defined but there is no corresponding rule registered" in case of internal symbols.

**Comment by vstakhov** [comment] 2019-04-03 14:46
Your configuration is broken. It id not an Rspamd issue.

**Comment by moisseev** [comment] 2019-04-03 14:48
Duplicate of #2797

**Comment by jendis** [comment] 2019-04-05 11:47
Ok, the reason is that modules managing listed symbols are disabled.
My suggestion is to stop printing this warning when module is disabled.

**Comment by vstakhov** [comment] 2019-04-05 13:10
Yes, I agree. The problem is that this fix is almost impossible for now as all symbols are registered usually with side effects so I cannot just load plugins and then disable symbols...

**Comment by jendis** [comment] 2019-04-05 14:25
Ok, thanks for explanation.
Either I'll close the issue or you'll add it on todo list?

**Closed** 2019-04-13 11:24 UTC
